---
title: "Data Cleaning"
author: "Clarissa Boyajian and Halina Do-Linh"
date: "1/24/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(janitor)
library(lubridate)
library(sf)
library(tidycensus)
library(patchwork)
library(scales)
library(tmap)
library(plotly)

options(scipen = 999)

source("../functions/function_acs_race.R")

# colors for racial groups
racial_group_colors <- 
  c("darkgreen", # asian
    "darkblue", # black
    "darkmagenta", # multiracial
    "darkred", # other
    "darkgoldenrod1", # white
    "darkorange2", # pacific_islander
    "darkcyan", # native_american
    "darkgrey" # hispanix_latinx
  )
# colors for agencies
agency_colors <- 
  c("#F8766D", # BOR
    "#7CAE00", # NPS
    "#00BFC4", # USFS
    "#C77CFF" # USACE
  )
```

```{r}
## 2018
# read in data
data_combined_2018 <- read.csv("../../../../data_clean/2018_joined_data.csv")

# ACS CA race data
zip_geometries_ca <- get_acs(geography = "zcta", year = 2018, geometry = TRUE, 
                             state = "California",
                             summary_var = "B01001_001",
                             variables = c(male = "B01001_002")) %>% 
  select(NAME, geometry) %>% 
  mutate(zip_code = str_sub(NAME, start = -5, end = -1)) %>% 
  select(zip_code, geometry)
# ACS US race data
zip_geometries_us <- get_acs(geography = "zcta", year = 2018, geometry = TRUE, 
                             summary_var = "B01001_001",
                             variables = c(male = "B01001_002")) %>% 
  select(NAME, geometry) %>% 
  mutate(zip_code = str_sub(NAME, start = -5, end = -1)) %>% 
  select(zip_code, geometry)
```



# VIZ

```{r}
data_map_santa_cruz_scorpion <- data_combined_2018 %>% 
  filter(park == "Santa Cruz Scorpion") %>% 
  group_by(customer_zip) %>% 
  summarize(number_reservations = n()) %>% 
  mutate(customer_zip = as.character(customer_zip))

data_map_geometries_ca <- zip_geometries_ca %>% 
  left_join(data_map_santa_cruz_scorpion, by = c("zip_code" = "customer_zip")) %>% 
  mutate(number_reservations = ifelse(is.na(number_reservations), 0, number_reservations))

data_map_geometries_us <- zip_geometries_us %>% 
  left_join(data_map_santa_cruz_scorpion, by = c("zip_code" = "customer_zip")) %>% 
  mutate(number_reservations = ifelse(is.na(number_reservations), 0, number_reservations))
```


```{r}
# hard to see without zoom ability
ggplot() +
  geom_sf(data = zip_geometries_us,
          col = "black") +
  geom_sf(data = data_map_geometries_us,
          aes(fill = number_reservations)) +
  scale_fill_distiller(palette = "BuPu")
```


```{r}
## transform zip codes to county level for visitor-shed??
tmap_mode("view")
tm_shape(data_map_geometries_ca) +
  tm_fill(col = "number_reservations",
          palette = "PuRd",
          style = "jenks",
          n = 10)

# tm_shape(data_map_geometries) +
#   tm_fill(col = "number_reservations",
#           palette = "magma",
#           style = "jenks",
#           n = 10)

```



