---
title: "Clean Data CA"
author: "Halina Do-Linh"
date: "1/23/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# attached packages
library(tidyverse)
library(janitor)
library(here)
```

# Read in agency datasets

```{r}
ridb_2020 <- read_csv(here("data", "FY20-historical-reservations-full.csv"))
```

# Tidy

```{r}
ridb_2020_clean <- ridb_2020 %>% 
  janitor::clean_names() %>% 
  select("historicalreservationid",
         "ordernumber",
         "agency",
         "orgid",
         "regioncode", "regiondescription",
         "parentlocationid", "parentlocation",
         "sitetype", "usetype",
         "productid", "inventorytype", 
         "facilityid", "facilityzip", "facilitystate", "facilitylongitude", "facilitylatitude",
         "customerzip", 
         "totalbeforetax",
         "discount", "totalpaid",
         "startdate", "enddate", "orderdate",
         "nights",
         "numberofpeople",
         "equipmentdescription", "equipmentlength") %>% 
  filter(facilitystate == "California") %>% 
  mutate(sitetype = tolower(sitetype)) %>% 
  filter(sitetype != c("historic tour",
                      "hiking zone",
                      "group picnic area",
                      "cave tour",
                      "management",
                      "anchorage",
                      "picnic",
                      "entry point",
                      "trailhead")) %>% 
  filter(usetype == "Overnight") %>% 
  mutate(nights = gsub(" days", "", nights)) %>% # used tidyverse gsub to remove day and days
  mutate(nights = as.numeric(gsub(" day", "", nights))) # make the column numeric instead of chr

```

