---
title: "Data Exploration"
author: "Clarissa Boyajian"
date: "1/12/2022"
output: 
html_document:
  df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(janitor)
library(gt)

dir.create(here::here("data"))
dir.create(here::here("agency_metadata_tables"))
```

## Load Data

```{r, eval=FALSE}
# Load raw data and choose columns to keep
raw_data <- read.csv("data/FY20_historical_reservations_full_raw.csv") %>% 
  select(agency, regioncode, regiondescription, parentlocation, park, sitetype, usetype, 
         inventorytype, facilityzip, facilitystate, facilitylongitude, 
         facilitylatitude, customerzip, customerstate, customercountry, 
         totalpaid, startdate, enddate, orderdate, nights, numberofpeople, 
         equipmentdescription)

# Split raw data by agency: create df for each unique agency
for (i in unique(raw_data$agency)) {
  assign(i, 
         raw_data %>% 
           filter(agency == i), 
         envir = .GlobalEnv)
}
```

```{r, eval=FALSE}
# Create CSV table of unique column values for agency called in function

agency_metadata_tables <- function(agency_df, title_as_string) {
  # Create lists of unique values in columns
  region_code <- 
    list(unique(agency_df$regioncode)) %>% 
    lapply(function(cell){ cell[!is.na(cell) & cell != ""]})
  region_description <- 
    list(unique(agency_df$regiondescription)) %>% 
    lapply(function(cell){ cell[!is.na(cell) & cell != ""]})
  parent_location <- 
    list(unique(agency_df$parentlocation)) %>% 
    lapply(function(cell){ cell[!is.na(cell) & cell != ""]})
  inventory_type <- 
    list(unique(agency_df$inventorytype)) %>% 
    lapply(function(cell){ cell[!is.na(cell) & cell != ""]})
  site_type <- 
    list(unique(agency_df$sitetype)) %>% 
    lapply(function(cell){ cell[!is.na(cell) & cell != ""]})
  facility_state <- 
    list(unique(agency_df$facilitystate)) %>% 
    lapply(function(cell){ cell[!is.na(cell) & cell != ""]})
  
  # calculate length of longest column
  table_length <- max(length(region_code), length(region_description),
                      length(parent_location), length(inventory_type),
                      length(site_type), length(facility_state)#,
                      #length(customer_state)
                      )
  
  # create data frame of columns
  df <- data.frame(matrix(nrow = table_length))
  df$region_code <- c(region_code, rep("", nrow(df)-length(region_code)))
  df$region_description <- c(region_description, rep("", nrow(df)-length(region_description)))
  df$parent_location <- c(parent_location, rep("", nrow(df)-length(parent_location)))
  df$facility_state <- c(facility_state, rep("", nrow(df)-length(facility_state)))
  df$site_type <- c(site_type, rep("", nrow(df)-length(site_type)))
  df$inventory_type <- c(inventory_type, rep("", nrow(df)-length(inventory_type)))
  #df$customer_state <- c(customer_state, rep("", nrow(df)-length(customer_state)))
  df <- df[-c(1)] %>%
  
  #write df to csv
  write.csv(df, paste0("agency_metadata_tables/", title_as_string, "_metadata.csv"), 
            append = FALSE)
}
```

```{r, eval=FALSE}
# Run function for all agencies

agency_metadata_tables(BLM, "BLM")
agency_metadata_tables(BOR, "BOR")
agency_metadata_tables(FWS, "FWS")
agency_metadata_tables(NARA, "NARA")
agency_metadata_tables(NPS, "NPS")
agency_metadata_tables(USACE, "USACE")
agency_metadata_tables(USFS, "USFS")
```


## Explore data

#### BLM
Bureau of Land Management

```{r}
BLM_metadata <- read.csv("agency_metadata_tables/BLM_metadata.csv")
BLM_metadata %>% gt() %>% tab_header(title = "BLM")
```

#### BOR
Bureau of Reclamation

```{r}
BOR_metadata <- read.csv("agency_metadata_tables/BOR_metadata.csv")
BOR_metadata %>% gt() %>% tab_header(title = "BOR")
```

#### FWS
Fish and Wildlife Services

```{r}
FWS_metadata <- read.csv("agency_metadata_tables/FWS_metadata.csv")
FWS_metadata %>% gt() %>% tab_header(title = "FWS")
```

#### NARA
National Archives and Records Administration

```{r}
NARA_metadata <- read.csv("agency_metadata_tables/NARA_metadata.csv")
NARA_metadata %>% gt() %>% tab_header(title = "NARA")
```

#### NPS
National Park Service

```{r}
NPS_metadata <- read.csv("agency_metadata_tables/NPS_metadata.csv")
NPS_metadata %>% gt() %>% tab_header(title = "NPS")
```

#### USACE
US Army Corps of Engineers

```{r}
USACE_metadata <- read.csv("agency_metadata_tables/USACE_metadata.csv")
USACE_metadata %>% gt() %>% tab_header(title = "USACE")
```

#### USFS
US Forest Service

```{r}
USFS_metadata <- read.csv("agency_metadata_tables/USFS_metadata.csv")
USFS_metadata %>% gt() %>% tab_header(title = "USFS")
```









