---
title: "Data Exploration - CA only"
author: "Clarissa Boyajian"
date: "1/17/2022"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(janitor)
library(gt)
library(sf)
library(tmap)
library(lubridate)
library(patchwork)
library(tidycensus)

dir.create(here::here("data")) # download data from RIDB and put in this file
dir.create(here::here("data/california_data"))
dir.create(here::here("figs"))

# connect to census API
# my_api_key <- source("census_api_key.R")
# census_api_key(my_api_key[1], install = TRUE, overwrite = TRUE)
```

```{r Load raw data}
# Load raw data for CA and choose columns to keep
raw_data <- read.csv("data/FY20_historical_reservations_full_raw.csv") %>% 
  filter(facilitystate == "California") %>% 
  select(agency, regioncode, regiondescription, parentlocation, park, sitetype, usetype, 
         inventorytype, facilityzip, facilitystate, facilitylongitude, 
         facilitylatitude, customerzip, customerstate, customercountry, 
         totalpaid, startdate, enddate, orderdate, nights, numberofpeople, 
         equipmentdescription)

# Filter just rows with customer zip code
subset_customer_zip <- raw_data %>% filter(customerzip != "") %>% 
  mutate(facilitylatitude = as.numeric(facilitylatitude),
         facilitylongitude = as.numeric(facilitylongitude),
         startdate = ymd_hms(startdate),
         enddate = ymd_hms(enddate),
         orderdate = ymd_hms(orderdate)) %>% 
  st_as_sf(coords = c("facilitylongitude", "facilitylatitude"),
           crs = 4326)
```

```{r Load census data}
# CA county geometries
ca_county_geom <- st_read("data/map_data/counties.shp") %>% 
  clean_names() %>% 
  rename(county_name = name)
st_crs(ca_county_geom) <- 4326

# Santa Barbara county only
santabarbara_county_geom <- ca_county_geom %>% filter(county_name == "Santa Barbara")

# Santa Barbara county zip codes
santa_barbara_zip_codes = c("93001", "93001", "93013", "93013", "93013", "93067", "93101", "93103", "93103", "93103", "93105", "93105", "93108", "93108", "93108", "93108", "93109", "93110", "93111", "93117", "93117", "93117", "93117", "93252", "93252", "93254", "93254", "93427", "93429", "93434", "93436", "93436", "93436", "93436", "93437", "93440", "93441", "93454", "93454", "93454", "93455", "93455", "93455", "93455", "93458", "93460", "93463", "93463", "93463", "93463", "93463")


# load list of all possible census variables
# test_census <- load_variables(2019, dataset = "acs5")
```

```{r}
## Subset and summarize for data exploration ##

# Filter out funky zip codes
subset_valid_customer_zip <- 
  subset_customer_zip[nchar(as.character(subset_customer_zip$customerzip)) == 5, ]

# summarize by park
park_summary <- subset_valid_customer_zip %>% 
  group_by(park) %>% 
  summarise(average_visitors_per_reservation = mean(numberofpeople, na.rm = TRUE),
            total_annual_visitors = sum(numberofpeople, na.rm = TRUE),
            average_paid = mean(totalpaid, na.rm = TRUE),
            total_paid = mean(totalpaid, na.rm = TRUE),
            average_length_stay_days = mean(interval(startdate, enddate) / 60 / 60 / 24, na.rm = TRUE),
            average_length_stay_days = mean(interval(orderdate, startdate) / 60 / 60 / 24, na.rm = TRUE))

# summarize by agency
agency_summary <- subset_valid_customer_zip %>% 
  group_by(agency) %>% 
  summarise(average_visitors_per_reservation = mean(numberofpeople, na.rm = TRUE),
            total_annual_visitors = sum(numberofpeople, na.rm = TRUE),
            average_paid = mean(totalpaid, na.rm = TRUE),
            total_paid = mean(totalpaid, na.rm = TRUE),
            average_length_stay_days = mean(interval(startdate, enddate) / 60 / 60 / 24, na.rm = TRUE),
            average_length_stay_days = mean(interval(orderdate, startdate) / 60 / 60 / 24, na.rm = TRUE))

# Santa Barbara subset
subset_santabarbara_valid_customer_zip <- subset_valid_customer_zip %>% 
  filter(facilityzip %in% santa_barbara_zip_codes)

santabarbara_park_summary <- subset_santabarbara_valid_customer_zip %>% 
  group_by(park) %>% 
  summarize(average_visitors_per_reservation = mean(numberofpeople, na.rm = TRUE),
            total_annual_visitors = sum(numberofpeople, na.rm = TRUE),
            average_paid = mean(totalpaid, na.rm = TRUE),
            total_paid = mean(totalpaid, na.rm = TRUE),
            average_length_stay_days = mean(interval(startdate, enddate) / 60 / 60 / 24, 
                                            na.rm = TRUE),
            average_length_stay_days = mean(interval(orderdate, startdate) / 60 / 60 / 24, 
                                            na.rm = TRUE))
```

```{r, eval=FALSE}
# save SB subset to drive
write_csv(as.data.frame(subset_santabarbara_valid_customer_zip), "data/santa_barbara_subset_valid_customer_zip.csv")
```


```{r Overview Graphs}
length_plot <- ggplot(agency_summary) +
  geom_col(aes(x = agency, 
               y = average_length_stay_days, 
               fill = agency),
           show.legend = FALSE) +
  scale_fill_discrete(type = "viridis") +
  labs(title = "Average Length of Reservation",
       x = "",
       y = "Days") +
  theme_classic()

average_visitors_plot <- ggplot(agency_summary) +
  geom_col(aes(x = agency, 
               y = average_visitors_per_reservation, 
               fill = agency),
           show.legend = FALSE) +
  scale_fill_discrete(type = "viridis") +
  labs(title = "Average Visitors per Reservation",
       x = "",
       y = "Individuals",
       fill = "Agency") +
  theme_classic()

average_cost_plot <- ggplot(agency_summary) +
  geom_col(aes(x = agency, 
               y = average_paid, 
               fill = agency),
           show.legend = FALSE) +
  scale_fill_discrete(type = "viridis") +
  labs(title = "Average Cost per Reservation",
       x = "",
       y = "US Dollars") +
  theme_classic()

annual_visitors_plot <- ggplot(agency_summary) +
  geom_col(aes(x = agency, 
               y = (total_annual_visitors / 1000), 
               fill = agency),
           show.legend = FALSE) +
  scale_fill_discrete(type = "viridis") +
  labs(title = "Total Visitors per Year",
       x = "",
       y = "1,000 Visitors") +
  theme_classic()

agency_plots <- 
  (length_plot + average_visitors_plot) / (average_cost_plot + annual_visitors_plot) + 
  plot_annotation(title = "Comparing Reservations in Califoria for Federal Public Lands in 2020",
                  caption = "Federal public agencies include: Bureau of Land Management (BLM), Bureau of Reclamation (BOR), \nNational Park Service (NPS), US Army Corps of Engineers (USACEO, and US Forest Service (USFS.")

agency_plots
```

```{r}
ggsave("figs/CA_agency_plots.jpg")
```



```{r CA map of parks}
tm_shape(ca_county_geom) + 
  tm_fill(col = "white") +
  tm_borders(col = "black", alpha = 0.5) +
tm_shape(park_summary) + 
  tm_dots(col = "total_annual_visitors")
```

```{r Santa Barbara map of parks}
tm_shape(santabarbara_county_geom) + 
  tm_fill(col = "white") +
  tm_borders(col = "black") +
tm_shape(santabarbara_park_summary) + 
  tm_bubbles(col = "total_annual_visitors", size = 0.25, style = "order")
```





