---
title: 'Data Visualization 240: Final Project'
author: "Clarissa Boyajian"
date: "3/8/2022"
output: pdf_document
---

```{r setup, include=FALSE, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(janitor)
library(tidycensus)
library(patchwork)

# load script to pull and clean ACS data
source("../analysis/functions/function_acs_race.R")

racial_group_colors <- c("Other" = "#999999", "Pacific Islander" = "#E69F00", "Multiracial" = "#56B4E9",
                              "Asian" = "#009E73", "Black" = "#F0E442", "White" = "#0072B2", 
                              "Native American" = "#D55E00", "Hispanic Latinx" = "#CC79A7")
```


```{r, include=FALSE}
# load joined RIDB and ACS dataframe
data_combined_2018 <- read_csv("../../../data_clean/2018_joined_data.csv")

# ACS CA race data
acs_subset_calculate_race(geography = "zcta", year = 2018, state = "California")

# ACS US race data
acs_subset_calculate_race(geography = "zcta", year = 2018, state = NULL)
```

# wrangle data for plots

```{r, include=FALSE}
# reservations in CA
data_plot_bar_race_nps <- data_combined_2018 %>%
  filter(agency == "NPS") %>% 
  summarize(white = (mean(white, na.rm = TRUE) * 100),
            black = (mean(black, na.rm = TRUE) * 100),
            asian = (mean(asian, na.rm = TRUE) * 100),
            multiracial = (mean(multiracial, na.rm = TRUE) * 100),
            other = (mean(other, na.rm = TRUE) * 100),
            native_american = (mean(native_american, na.rm = TRUE) * 100),
            pacific_islander = (mean(pacific_islander, na.rm = TRUE) * 100),
            hispanic_latinx = (mean(hispanic_latinx, na.rm = TRUE) * 100)) %>%
  pivot_longer(cols = 1:8, names_to = "race", values_to = "race_percent_average") %>% 
  mutate(race = str_replace(string = race,
                            pattern = "_",
                            replacement = " "),
         race = str_to_title(race))
data_plot_bar_race_nps$race <- with(data_plot_bar_race, reorder(race, race_percent_average))

data_plot_bar_race_usfs <- data_combined_2018 %>%
  filter(agency == "USFS") %>% 
  summarize(white = (mean(white, na.rm = TRUE) * 100),
            black = (mean(black, na.rm = TRUE) * 100),
            asian = (mean(asian, na.rm = TRUE) * 100),
            multiracial = (mean(multiracial, na.rm = TRUE) * 100),
            other = (mean(other, na.rm = TRUE) * 100),
            native_american = (mean(native_american, na.rm = TRUE) * 100),
            pacific_islander = (mean(pacific_islander, na.rm = TRUE) * 100),
            hispanic_latinx = (mean(hispanic_latinx, na.rm = TRUE) * 100)) %>%
  pivot_longer(cols = 1:8, names_to = "race", values_to = "race_percent_average") %>% 
  mutate(race = str_replace(string = race,
                            pattern = "_",
                            replacement = " "),
         race = str_to_title(race))
data_plot_bar_race_usfs$race <- with(data_plot_bar_race, reorder(race, race_percent_average))
```


```{r, include=FALSE}
# CA population
data_plot_bar_race_ca <- data_acs_2018_race_percent_California %>%
  summarize(white = (mean(white, na.rm = TRUE) * 100),
            black = (mean(black, na.rm = TRUE) * 100),
            asian = (mean(asian, na.rm = TRUE) * 100),
            multiracial = (mean(multiracial, na.rm = TRUE) * 100),
            other = (mean(other, na.rm = TRUE) * 100),
            native_american = (mean(native_american, na.rm = TRUE) * 100),
            pacific_islander = (mean(pacific_islander, na.rm = TRUE) * 100),
            hispanic_latinx = (mean(hispanic_latinx, na.rm = TRUE) * 100)) %>%
  pivot_longer(cols = 1:8, names_to = "race", values_to = "race_percent_average") %>% 
  mutate(race = str_replace(string = race,
                            pattern = "_",
                            replacement = " "),
         race = str_to_title(race))
data_plot_bar_race_ca$race <- with(data_plot_bar_race_ca, reorder(race, race_percent_average))
```


```{r, include=FALSE}
# US population
data_plot_bar_race_us <- data_acs_2018_race_percent %>%
  summarize(white = (mean(white, na.rm = TRUE) * 100),
            black = (mean(black, na.rm = TRUE) * 100),
            asian = (mean(asian, na.rm = TRUE) * 100),
            multiracial = (mean(multiracial, na.rm = TRUE) * 100),
            other = (mean(other, na.rm = TRUE) * 100),
            native_american = (mean(native_american, na.rm = TRUE) * 100),
            pacific_islander = (mean(pacific_islander, na.rm = TRUE) * 100),
            hispanic_latinx = (mean(hispanic_latinx, na.rm = TRUE) * 100)) %>%
  pivot_longer(cols = 1:8, names_to = "race", values_to = "race_percent_average") %>% 
  mutate(race = str_replace(string = race,
                            pattern = "_",
                            replacement = " "),
         race = str_to_title(race))
data_plot_bar_race_us$race <- with(data_plot_bar_race_us, reorder(race, race_percent_average))
```


```{r, include=FALSE}
data_plot_bar_race_ridb_ca_nps <- data_plot_bar_race_nps %>% 
  left_join(y = data_plot_bar_race_ca,
            by = c("race"),
            suffix = c("_ridb", "_ca")) %>% 
  rename(RIDB = race_percent_average_ridb,
         CA = race_percent_average_ca) %>% 
  pivot_longer(cols = 2:3,
               names_to = "data_source",
               values_to = "race_percent_average") %>% 
  mutate(data_source = factor(data_source, levels = c("RIDB", "CA")))

data_plot_bar_race_ridb_ca_usfs <- data_plot_bar_race_usfs %>% 
  left_join(y = data_plot_bar_race_ca,
            by = c("race"),
            suffix = c("_ridb", "_ca")) %>% 
  rename(RIDB = race_percent_average_ridb,
         CA = race_percent_average_ca) %>% 
  pivot_longer(cols = 2:3,
               names_to = "data_source",
               values_to = "race_percent_average") %>% 
  mutate(data_source = factor(data_source, levels = c("RIDB", "CA")))
```



# Visualizations: Comparative graphs

```{r, echo=FALSE, fig.width=18, fig.height=10}
# plot for shiny app
plot_col_race_ridb_ca_nps <- 
  ggplot(data = data_plot_bar_race_ridb_ca_nps) +
  geom_col(aes(x = race_percent_average,
               y = race,
               fill = data_source),
           stat = "identity",
           position = "identity", alpha = 0.5) +
  scale_fill_manual(values = c("RIDB" = "blue", "CA" = "red")) +  
  geom_text(aes(x = race_percent_average,
                y = race,
                label = paste0(round(race_percent_average, 1), "%"),
                col = data_source), 
            position = position_dodge(width = 0.7), hjust = -0.1, size = 8) +
  scale_color_manual(values = c("RIDB" = "navy", "CA" = "darkred")) +
  labs(x = "Average percentage of race (%)",
       y = "Race",
       fill = "Race",
       title = "Racial Breakdown of ZIP Codes in 2018",
       subtitle = "Visitors' home ZIP codes for National Park Service Overnight Reservations in California \nvs. California Residents") +
  theme_minimal() +
  theme(plot.background = element_rect("white"),
        axis.text = element_text(size = 20),
        axis.title = element_text(size = 22, face = "bold"),
        title = element_text(size = 24, face = "bold"),
        legend.position = "none",
        panel.grid.major.y = element_blank()) +
  scale_x_continuous(limits = c(0, 60), breaks = seq(0, 60, 10), minor_breaks = seq(0, 60, 5))

plot_col_race_ridb_ca_nps
```


```{r, echo=FALSE, fig.width=18, fig.height=10}
# plot for shiny app
plot_col_race_ridb_ca_usfs <- 
  ggplot(data = data_plot_bar_race_ridb_ca_usfs) +
  geom_col(aes(x = race_percent_average,
               y = race,
               fill = data_source),
           stat = "identity",
           position = "identity", alpha = 0.5) +
  scale_fill_manual(values = c("RIDB" = "blue", "CA" = "red")) +  
  geom_text(aes(x = race_percent_average,
                y = race,
                label = paste0(round(race_percent_average, 1), "%"),
                col = data_source), 
            position = position_dodge(width = 0.7), hjust = -0.1, size = 8) +
  scale_color_manual(values = c("RIDB" = "navy", "CA" = "darkred")) +
  labs(x = "Average percentage of race (%)",
       y = "Race",
       fill = "Race",
       title = "Racial Breakdown of ZIP Codes in 2018",
       subtitle = "Visitors' home ZIP codes for US Forest Service Overnight Reservations in California \nvs. California Residents") +
  theme_minimal() +
  theme(plot.background = element_rect("white"),
        axis.text = element_text(size = 20),
        axis.title = element_text(size = 22, face = "bold"),
        title = element_text(size = 24, face = "bold"),
        legend.position = "none",
        panel.grid.major.y = element_blank()) +
  scale_x_continuous(limits = c(0, 60), breaks = seq(0, 60, 10), minor_breaks = seq(0, 60, 5))

plot_col_race_ridb_ca_usfs
```




```{r, echo=FALSE}
# create plot of reservations in CA
plot_bar_race <- ggplot(data = data_plot_bar_race) +
  geom_col(aes(x = race_percent_average,
               y = race, 
               fill = race)) +
  labs(x = "Average proportion of race in home ZIP codes (overnight reservations in CA)",
       y = "Race",
       fill = "Race",
       title = "Racial Breakdown of Visitors' Home ZIP Codes \nfor Overnight Reservations in California in 2018") +
  theme_minimal() +
  theme(plot.background = element_rect("white"),
        # axis.text = element_text(size = 16),
        # axis.title = element_text(size = 18, face = "bold"),
        # title = element_text(size = 20, face = "bold"),
        legend.position = "none",
        panel.grid.major.y = element_blank()) +
  scale_fill_manual(values = racial_group_colors) +
  scale_x_continuous(limits = c(0, 0.8), breaks = seq(0, 0.8, 0.1), minor_breaks = seq(0, 0.8, 0.025))
```

```{r, echo=FALSE}
# create plot of population in CA
plot_bar_race_ca <- ggplot(data = data_plot_bar_race_ca) +
  geom_col(aes(x = race_percent_average,
               y = race, 
               fill = race)) +
  labs(x = "Average proportion of race in home ZIP codes (residents of CA)",
       y = "Race",
       fill = "Race",
       title = "Racial Breakdown of Home ZIP Codes\nfor California in 2018") +
  theme_minimal() +
  theme(plot.background = element_rect("white"),
        # axis.text = element_text(size = 16),
        # axis.title = element_text(size = 18, face = "bold"),
        # title = element_text(size = 20, face = "bold"),
        legend.position = "none",
        panel.grid.major.y = element_blank()) +
  scale_fill_manual(values = racial_group_colors) +
  scale_x_continuous(limits = c(0, 0.8), breaks = seq(0, 0.8, 0.1), minor_breaks = seq(0, 0.8, 0.025))
```

```{r, echo=FALSE}
# create plot of population in CA
plot_bar_race_us <- ggplot(data = data_plot_bar_race_us) +
  geom_col(aes(x = race_percent_average,
               y = race, 
               fill = race)) +
  labs(x = "Average proportion of race in home ZIP codes (residents of US",
       y = "Race",
       fill = "Race",
       title = "Racial Breakdown of Home ZIP Codes\nfor United States in 2018") +
  theme_minimal() +
  theme(plot.background = element_rect("white"),
        # axis.text = element_text(size = 16),
        # axis.title = element_text(size = 18, face = "bold"),
        # title = element_text(size = 20, face = "bold"),
        legend.position = "none",
        panel.grid.major.y = element_blank()) +
  scale_fill_manual(values = racial_group_colors) +
  scale_x_continuous(limits = c(0, 0.8), breaks = seq(0, 0.8, 0.1), minor_breaks = seq(0, 0.8, 0.025))
```


```{r, echo=FALSE, fig.height=16, fig.width=16}
plot_bar_race_combined <- 
plot_bar_race / plot_bar_race_ca / plot_bar_race_us

plot_bar_race_combined
```

## Visualizations: Difference graphs

```{r, include=FALSE}
data_plot_difference_race <- left_join(x = data_plot_bar_race, 
                                       y = data_plot_bar_race_ca,
                                       by = "race") %>% 
  rename(percent_ridb = race_percent_average.x, 
         percent_ca = race_percent_average.y) %>% 
  left_join(y = data_plot_bar_race_us, by = "race") %>% 
  rename(percent_us = race_percent_average) %>% 
  mutate(percent_diff_ridb_ca = percent_ridb - percent_ca,
         percent_diff_ridb_us = percent_ridb - percent_us)

```

```{r, echo=FALSE}
plot_bar_race_diff_ridb_ca <- ggplot(data = data_plot_difference_race) +
  geom_col(aes(x = percent_diff_ridb_ca,
               y = race, 
               fill = race)) +
  labs(x = "Difference in average proportion of race in home ZIP codes (RIDB - CA)",
       y = "Race",
       fill = "Race",
       title = "Difference in Racial Breakdown of Home ZIP Codes for \nCalifornia Residents Compared to Overnight Reservations \nin California in 2018") +
  theme_minimal() +
  theme(plot.background = element_rect("white"),
        # axis.text = element_text(size = 18),
        # axis.title = element_text(size = 18, face = "bold"),
        # title = element_text(size = 20, face = "bold"),
        legend.position = "none",
        panel.grid.major.y = element_blank()) +
  scale_fill_manual(values = racial_group_colors)
```

```{r, echo=FALSE}
plot_bar_race_diff_ridb_us <- ggplot(data = data_plot_difference_race) +
  geom_col(aes(x = percent_diff_ridb_us,
               y = race, 
               fill = race)) +
  labs(x = "Difference in average proportion of race in home ZIP codes (RIDB - US)",
       y = "Race",
       fill = "Race",
       title = "Difference in Racial Breakdown of Home ZIP Codes for \nUnited States Residents Compared to Overnight Reservations \nin California in 2018") +
  theme_minimal() +
  theme(plot.background = element_rect("white"),
        # axis.text = element_text(size = 18),
        # axis.title = element_text(size = 18, face = "bold"),
        # title = element_text(size = 20, face = "bold"),
        legend.position = "none",
        panel.grid.major.y = element_blank()) +
  scale_fill_manual(values = racial_group_colors)
```

```{r, echo=FALSE, fig.width=16, fig.height=14}
plot_bar_race_diff_combined <- 
plot_bar_race_diff_ridb_ca / plot_bar_race_diff_ridb_us +
  plot_annotation(caption = "Positive values indicate an overrepresentation of a given racial group in visitors' home ZIP codes as compared \nto the overall population of California or the United Sate and negative values indicate an underrepresentation.")

plot_bar_race_diff_combined
```


```{r, eval=FALSE}
ggsave(plot = plot_bar_race_combined, filename = "../figs/plot_bar_race_combined.png",
       width = 16, height = 18)

ggsave(plot = plot_bar_race_diff_combined, filename = "../figs/plot_bar_race_diff.png", 
       width = 16, height = 14)

ggsave(plot = plot_col_race_ridb_ca_nps, filename = "../figs/plot_col_race_ridb_ca_overlay_nps.png",
       width = 22, height = 10)

ggsave(plot = plot_col_race_ridb_ca_usfs, filename = "../figs/plot_col_race_ridb_ca_overlay_usfs.png",
       width = 22, height = 10)
```



