---
title: "Visitor-shed maps"
author: "Clarissa"
date: "3/18/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

library(tidyverse)
library(here)
library(janitor)
library(lubridate)
library(sf)
library(tidycensus)
library(zipcodeR)
library(tmap)
library(vroom)
library(paletteer)
library(scales)
library(tigris)

options(scipen = 999)

tmap_mode("view")
```


```{r load data, message=FALSE}
# read in RIDB/ACS data
data_ridb_acs_2018 <- vroom(file = "../../../../data_clean/2018_joined_data.csv",
                            delim = ",") ## non-map graphs (no geometries)
# data_ridb_acs_2018 <- readRDS(file = "../../../../data_clean/2018_joined_data.rds") ## maps (don't use RDS for non-map viz, too slow)


# ZIP code geometries
zip_geometries_ca <- get_acs(geography = "zcta", year = 2018, geometry = TRUE, 
                             state = "California",
                             summary_var = "B01001_001",
                             variables = c(male = "B01001_002")) %>% 
  select(NAME, geometry) %>% 
  mutate(zip_code = str_sub(NAME, start = -5, end = -1)) %>% 
  select(zip_code, geometry)

# state geometries
state_geometries_us <- get_acs(geography = "state", year = 2018, geometry = TRUE, 
                             summary_var = "B01001_001",
                             variables = c(male = "B01001_002")) %>% 
  select(GEOID, NAME, geometry) %>% 
  rename(fips = GEOID, state = NAME)

# states for each ZIP code
fips_list <- c("01", "02", "04", "05", "06", "08", "09", "10", "11", "12", 
               "13", "15", "16", "17", "18", "19", "20", "21", "22", "23", 
               "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", 
               "34", "35", "36", "37", "38", "39", "40", "41", "42", "44", 
               "45", "46", "47", "48", "49", "50", "51", "53", "54", "55", 
               "56", "72")
df_states_fips <- as.data.frame(list(fips = fips_list,
                                     state = c("AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "DC", "FL",
                                               "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME",
                                               "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH",
                                               "NJ", "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI",
                                               "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI",
                                               "WY", "PR")))

df_states_zip_codes <- data.frame()

for (i in seq_along(fips_list)){
  state <- search_fips(state_fips = fips_list[[i]]) %>% 
    select(zipcode, state)
  df_states_zip_codes <- rbind(df_states_zip_codes, state)
}

df_states_fips_zip_codes <- df_states_zip_codes %>% 
  left_join(y = df_states_fips,
            by = "state") %>% 
  rename(zip_state_abbr = state,
         zip_fips = fips)
```


# Visitor-shed for Upper Pines, Yosemite

```{r}
## -- data wrangle -- ##
data_map_us_yosemite_upper_pines <- data_ridb_acs_2018 %>% 
  filter(park == "Upper Pines") %>% 
  left_join(y = df_states_fips_zip_codes,
            by = c("customer_zip" = "zipcode")) %>% 
  group_by(zip_state_abbr, zip_fips) %>% 
  summarize(number_reservations = n()) %>% 
  filter(!is.na(zip_state_abbr))

data_map_us_yosemite_upper_pines_geometries_us <- 
  state_geometries_us %>% 
  left_join(y = data_map_us_yosemite_upper_pines,
            by = c("fips" = "zip_fips"))


## -- create plot -- ##

tm_shape(data_map_us_yosemite_upper_pines_geometries_us) +
  tm_borders(col = "grey", alpha = 0.5) +
  tm_fill(col = "number_reservations",
          title = "Number of Visits",
          palette = "YlGn",
          n = 10, 
          style = "jenks",
          id = "zip_state_abbr", 
          popup.vars = c("Total Visits" = "number_reservations")) +
  tm_view(set.view = c(-101.834335, 40.022356, 3))
```


# Visitor-shed for Hope Valley, Humboldt-Toiyabe National Forest

```{r}
## -- data wrangle -- ##
data_map_us_humboldt_hope_valley <- data_ridb_acs_2018 %>% 
  filter(park == "Hope Valley") %>% 
  left_join(y = df_states_fips_zip_codes,
            by = c("customer_zip" = "zipcode")) %>% 
  group_by(zip_state_abbr, zip_fips) %>% 
  summarize(number_reservations = n()) %>% 
  filter(!is.na(zip_state_abbr))

data_map_us_humboldt_hope_valley_geometries_us <- 
  state_geometries_us %>% 
  left_join(y = data_map_us_humboldt_hope_valley,
            by = c("fips" = "zip_fips"))


## -- create plot -- ##

tm_shape(data_map_us_humboldt_hope_valley_geometries_us) +
  tm_borders(col = "grey", alpha = 0.5) +
  tm_fill(col = "number_reservations",
          title = "Number of Visits",
          palette = "YlGn",
          n = 10, 
          style = "jenks",
          id = "zip_state_abbr", 
          popup.vars = c("Total Visits" = "number_reservations")) +
  tm_view(set.view = c(-101.834335, 40.022356, 3))
```



# CA Visitor-shed for Upper Pines, Yosemite

```{r}
## -- data wrangle -- ##
data_map_ca_yosemite_upper_pines <- data_ridb_acs_2018 %>% 
  filter(park == "Upper Pines") %>% 
  group_by(customer_zip) %>% 
  summarize(number_reservations = n()) %>% 
  mutate(customer_zip = as.character(customer_zip))

data_map_ca_yosemite_upper_pines_zip_geometries_ca <- zip_geometries_ca %>% 
  left_join(data_map_ca_yosemite_upper_pines, by = c("zip_code" = "customer_zip")) %>% 
  mutate(number_reservations = ifelse(is.na(number_reservations), 0, number_reservations))

data_map_ca_yosemite_upper_pines_geom <- data_ridb_acs_2018 %>% 
  filter(park == "Upper Pines") %>% 
  group_by(agency, admin_unit, park) %>% 
  summarise(facility_latitude = median(facility_latitude),
            facility_longitude = median(facility_longitude)) %>% 
  st_as_sf(coords = c("facility_latitude", "facility_longitude"),
           crs = 4326) %>% 
  st_transform(crs = 4269) # using NAD83 because measured in meters


## -- create plot -- ##

tm_shape(data_map_ca_yosemite_upper_pines_zip_geometries_ca) +
  tm_fill(col = "number_reservations",
          title = "Number of Visits",
          palette = "PuRd",
          style = "jenks",
          n = 10, 
          popup.vars = c("Total Visits" = "number_reservations")) +
  tm_shape(data_map_ca_yosemite_upper_pines_geom) +
  tm_dots(col = "#009900FF", size = 0.1, alpha = 0.9,
          id = "park") +
  tm_view(set.view = c(-119.559917, 37.061753, 6))
```


# CA Visitor-shed for Hope Valley, Humboldt-Toiyabe National Forest

```{r}
## -- data wrangle -- ##
data_map_ca_humboldt_hope_valley <- data_ridb_acs_2018 %>% 
  filter(park == "Hope Valley") %>% 
  group_by(customer_zip) %>% 
  summarize(number_reservations = n()) %>% 
  mutate(customer_zip = as.character(customer_zip))

data_map_ca_humboldt_hope_valley_geometries_ca <- zip_geometries_ca %>% 
  left_join(data_map_ca_humboldt_hope_valley, by = c("zip_code" = "customer_zip")) %>% 
  mutate(number_reservations = ifelse(is.na(number_reservations), 0, number_reservations))

data_map_ca_humboldt_hope_valley_geom <- data_ridb_acs_2018 %>% 
  filter(park == "Hope Valley") %>% 
  group_by(agency, admin_unit, park) %>% 
  summarise(facility_latitude = median(facility_latitude),
            facility_longitude = median(facility_longitude)) %>% 
  st_as_sf(coords = c("facility_latitude", "facility_longitude"),
           crs = 4326) %>% 
  st_transform(crs = 4269) # using NAD83 because measured in meters


## -- create plot -- ##

tm_shape(data_map_ca_humboldt_hope_valley_geometries_ca) +
  tm_fill(col = "number_reservations",
          title = "Number of Visits",
          palette = "PuRd",
          style = "jenks",
          n = 10, 
          popup.vars = c("Total Visits" = "number_reservations")) +
  tm_shape(data_map_ca_humboldt_hope_valley_geom) +
  tm_dots(col = "#009900FF", size = 0.1, alpha = 0.75,
          id = "park",
          popup.vars = c("Agency" = "agency", "Admin Unit" = "admin_unit", 
                         "Park" = "park")) +
  tm_view(set.view = c(-119.559917, 37.061753, 6))
```



# Save plot all data to RDS

```{r, eval=FALSE}
plot_data <- c("data_map_us_yosemite_upper_pines_geometries_us", "data_map_us_humboldt_hope_valley_geometries_us",
               "data_map_ca_yosemite_upper_pines_zip_geometries_ca", "data_map_ca_yosemite_upper_pines_geom",
               "data_map_ca_humboldt_hope_valley_geometries_ca", "data_map_ca_humboldt_hope_valley_geom")

for (i in seq_along(plot_data)){
  saveRDS(object = get(plot_data[[i]]),
          file = paste0("../../../../data_clean/2018_data_map_visitorshed/2018_", 
                        plot_data[[i]],
                        ".rds"))
}
```

