---
title: "Mock up of 'Data Summary'"
author: ""
date: "4/10/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

library(tidyverse)
library(here)
library(janitor)
library(lubridate)
library(tidycensus)
library(patchwork)
library(scales)
library(vroom)
library(paletteer)
library(plotly)

options(scipen = 999)

# load script to pull and clean ACS data
source("../functions/function_acs_race.R")
source("../functions/function_acs_median_income.R")
source("../functions/function_acs_education.R")
source("../functions/function_acs_language.R")
```


```{r load data}
# read in joined data
data_ridb_acs_2018 <- vroom(file = "../../../../data_clean/2018_joined_data.csv",
                            delim = ",")
# data_ridb_acs_2018 <- readRDS(file = "../../../../data_clean/2018_joined_data.rds") # don't use RDS for non-map viz

# ACS CA data
# acs_subset_calculate_race(geography = "zcta", year = 2018, state = "California")
# acs_subset_calculate_education(geography = "zcta", year = 2018, state = "California")
# acs_subset_calculate_language(geography = "zcta", state = "California")
# acs_subset_calculate_median_income(geography = "zcta", year = 2018, state = "California")
# data_acs_2018_median_income_California <- data_acs_2018_median_income_California %>% 
#   left_join(y = data_acs_2018_education_percent_California,
#             by = "zip_code") %>% 
#   select(zip_code, median_income, zip_code_population)
```


## Data Summary

### Distance traveled

#### All reservations in 2018

```{r}
## -- data wrangle -- ##
data_plot_distance_traveled_all <- data_ridb_acs_2018 %>% 
  mutate(distance_traveled_mi = distance_traveled_m * 0.000621371) %>% 
  select(agency, admin_unit, park, distance_traveled_mi) %>% 
  filter(!is.na(distance_traveled_mi))


## -- create plot -- ##

# parameters
hist_colors <- c("#009900FF", "#00c000")

# plot_1 for shiny app
x_max <- (round(max(data_plot_distance_traveled_all$distance_traveled_mi) / 5) * 5) + 5 # max x rounded to nearest 5
center_bin <- 
  if (max(data_plot_distance_traveled_all$distance_traveled_mi) > 100) {
    round((max(data_plot_distance_traveled_all$distance_traveled_mi) / 100) / 5) * 5
  } else if (max(data_plot_distance_traveled_all$distance_traveled_mi) > 10) {
    round((max(data_plot_distance_traveled_all$distance_traveled_mi) / 10) / 5) * 5
  } else {
    0.5
  }
quant_80 <- quantile(x = data_plot_distance_traveled_all$distance_traveled_mi,
                     probs = seq(0, 1, 0.1))[[9]] %>% round(0)
split_all <- data.frame(table(cut(x = data_plot_distance_traveled_all$distance_traveled_mi, 
                                       breaks = seq(0, 
                                                    x_max,
                                                    center_bin * 2))))

plot_distance_traveled_1 <-
  ggplot(data = data_plot_distance_traveled_all) +
  geom_histogram(aes(x = distance_traveled_mi,
                     text = paste0(scales::comma(round(..count.. / nrow(data_plot_distance_traveled_all), 2) * 100), 
                                   "% of all reservations traveled between ", xmin, " and ", xmax, " miles",
                                   "<br>(", scales::comma(..count..), " reservations)")),
                 binwidth = center_bin * 2,
                 center = center_bin,
                 fill = hist_colors[[1]], 
                 col = hist_colors[[2]], size = 0.05) +
  scale_x_continuous(limits = c(0, x_max)) +
  scale_y_continuous(labels = scales::comma) +
  geom_vline(xintercept = quant_80,
             linetype = "dashed", alpha = 0.5, color = "darkred") +
  labs(x = "Distance traveled (miles)",
       y = "",
       title = "Distance Traveled to Reservation for <br> All Overnight Reservations in California in 2018") +
  theme_minimal() +
  theme(plot.background = element_rect("white"),
        panel.grid.major.y = element_blank())
```


```{r}
ggplotly(plot_distance_traveled_1,
         tooltip = list("text")) %>% 
  layout(margin = list(b = 130, t = 100), 
         annotations =  list(x = 1, 
                             y = -0.35, 
                             text = paste0("80% of reservations to California overnight sites in ",
                                           deparse(substitute(data_ridb_acs_2018)) %>% str_remove(".*_"),
                                           " traveled less than ", quant_80, " miles."), 
                             showarrow = F, 
                             xre = 'paper', yref = 'paper', 
                             xanchor = 'left', 
                             yancho = 'auto', 
                             xshift = 0, yshift = 0,
                             font = list(size = 12, color = "darkred")))
```




#### All reservations to Yosemite, Upper Pines in 2018 (highly visited campground)

```{r}
## -- data wrangle -- ##
data_plot_distance_traveled_upperpines <- data_ridb_acs_2018 %>% 
  filter(park == "Upper Pines") %>% 
  mutate(distance_traveled_mi = distance_traveled_m * 0.000621371) %>% 
  select(agency, admin_unit, park, distance_traveled_mi) %>% 
  filter(!is.na(distance_traveled_mi))

quant_80 <- quantile(x = data_plot_distance_traveled_upperpines$distance_traveled_mi,
                     probs = seq(0, 1, 0.1))[[9]] %>% round(0)

## -- create plot -- ##

# parameters
hist_colors <- c("#009900FF", "#00c000")

# plot_1 for shiny app
x_max <- (round(max(data_plot_distance_traveled_upperpines$distance_traveled_mi) / 5) * 5) + 5 # max x rounded to nearest 5
center_bin <- 
  if (max(data_plot_distance_traveled_upperpines$distance_traveled_mi) > 100) {
    round((max(data_plot_distance_traveled_upperpines$distance_traveled_mi) / 100) / 5) * 5
  } else if (max(data_plot_distance_traveled_upperpines$distance_traveled_mi) > 10) {
    round((max(data_plot_distance_traveled_upperpines$distance_traveled_mi) / 10) / 5) * 5
  } else {
    0.5
  }

split_all <- data.frame(table(cut(x = data_plot_distance_traveled_upperpines$distance_traveled_mi, 
                                       breaks = seq(0, 
                                                    x_max,
                                                    center_bin * 2))))

plot_distance_traveled_upperpines <-
  ggplot(data = data_plot_distance_traveled_upperpines) +
  geom_histogram(aes(x = distance_traveled_mi,
                     text = paste0(scales::comma(round(..count.. / nrow(data_plot_distance_traveled_upperpines), 2) * 100), 
                                   "% of all reservations traveled between ", xmin, " and ", xmax, " miles",
                                   "<br>(", scales::comma(..count..), " reservations)")),
                 binwidth = center_bin * 2,
                 center = center_bin,
                 fill = hist_colors[[1]], 
                 col = hist_colors[[2]], size = 0.05) +
  scale_x_continuous(limits = c(0, x_max)) +
  scale_y_continuous(labels = scales::comma) +
  geom_vline(xintercept = quant_80,
             linetype = "dashed", alpha = 0.5, color = "darkred") +
  labs(x = "Distance traveled (miles)",
       y = "",
       title = "Distance Traveled to Reservation for <br>Upper Pines, Yosemite National Park in 2018") +
  theme_minimal() +
  theme(plot.background = element_rect("white"),
        panel.grid.major.y = element_blank())
```


```{r}
ggplotly(plot_distance_traveled_upperpines,
         tooltip = list("text")) %>% 
  layout(margin = list(b = 130, t = 100), 
         annotations =  list(x = 1, 
                             y = -0.35, 
                             text = paste0("80% of reservations to California overnight sites in ",
                                           deparse(substitute(data_ridb_acs_2018)) %>% str_remove(".*_"),
                                           " traveled less than ", quant_80, " miles."), 
                             showarrow = F, 
                             xre = 'paper', yref = 'paper', 
                             xanchor = 'left', 
                             yancho = 'auto', 
                             xshift = 0, yshift = 0,
                             font = list(size = 12, color = "darkred")))
```


#### ALl reservations to Sierra NF, Crane Valley in 2018 (medium distance traveled)

```{r}
## -- data wrangle -- ##
data_plot_distance_traveled_cranevalley <- data_ridb_acs_2018 %>% 
  filter(park == "Crane Valley") %>% 
  mutate(distance_traveled_mi = distance_traveled_m * 0.000621371) %>% 
  select(agency, admin_unit, park, distance_traveled_mi) %>% 
  filter(!is.na(distance_traveled_mi))

quant_80 <- quantile(x = data_plot_distance_traveled_cranevalley$distance_traveled_mi,
                     probs = seq(0, 1, 0.1))[[9]] %>% round(0)

## -- create plot -- ##

# parameters
hist_colors <- c("#009900FF", "#00c000")

# plot_1 for shiny app
x_max <- (round(max(data_plot_distance_traveled_cranevalley$distance_traveled_mi) / 5) * 5) + 10 # max x rounded to nearest 5
center_bin <- 
  if (max(data_plot_distance_traveled_cranevalley$distance_traveled_mi) > 100) {
    round((max(data_plot_distance_traveled_cranevalley$distance_traveled_mi) / 100) / 5) * 5
  } else if (max(data_plot_distance_traveled_cranevalley$distance_traveled_mi) > 10) {
    round((max(data_plot_distance_traveled_cranevalley$distance_traveled_mi) / 10) / 5) * 5
  } else {
    0.5
  }

split_all <- data.frame(table(cut(x = data_plot_distance_traveled_cranevalley$distance_traveled_mi, 
                                       breaks = seq(0, 
                                                    x_max,
                                                    center_bin * 2))))

plot_distance_traveled_cranevalley <-
  ggplot(data = data_plot_distance_traveled_cranevalley) +
  geom_histogram(aes(x = distance_traveled_mi,
                     text = paste0(scales::comma(round(..count.. / nrow(data_plot_distance_traveled_cranevalley), 2) * 100), 
                                   "% of all reservations traveled between ", xmin, " and ", xmax, " miles",
                                   "<br>(", scales::comma(..count..), " reservations)")),
                 binwidth = center_bin * 2,
                 center = center_bin,
                 fill = hist_colors[[1]], 
                 col = hist_colors[[2]], size = 0.05) +
  scale_x_continuous(limits = c(0, x_max)) +
  scale_y_continuous(labels = scales::comma) +
  geom_vline(xintercept = quant_80,
             linetype = "dashed", alpha = 0.5, color = "darkred") +
  labs(x = "Distance traveled (miles)",
       y = "",
       title = "Distance Traveled to Reservation for <br>Crane Valley, Sierra National Forest in 2018") +
  theme_minimal() +
  theme(plot.background = element_rect("white"),
        panel.grid.major.y = element_blank())
```


```{r}
ggplotly(plot_distance_traveled_cranevalley,
         tooltip = list("text")) %>% 
  layout(margin = list(b = 130, t = 100), 
         annotations =  list(x = 1, 
                             y = -0.35, 
                             text = paste0("80% of reservations to California overnight sites in ",
                                           deparse(substitute(data_ridb_acs_2018)) %>% str_remove(".*_"),
                                           " traveled less than ", quant_80, " miles."), 
                             showarrow = F, 
                             xre = 'paper', yref = 'paper', 
                             xanchor = 'left', 
                             yancho = 'auto', 
                             xshift = 0, yshift = 0,
                             font = list(size = 12, color = "darkred")))
```


#### All reservations to Los Padres, Navajo Flats in 2018 (low visits, lowest mean distance traveled)


```{r}
## -- data wrangle -- ##
data_plot_distance_traveled_navajoflats <- data_ridb_acs_2018 %>% 
  filter(park == "Navajo Flats Campground") %>% 
  mutate(distance_traveled_mi = distance_traveled_m * 0.000621371) %>% 
  select(agency, admin_unit, park, distance_traveled_mi) %>% 
  filter(!is.na(distance_traveled_mi))

quant_80 <- quantile(x = data_plot_distance_traveled_navajoflats$distance_traveled_mi,
                     probs = seq(0, 1, 0.1))[[9]] %>% round(0)


## -- create plot -- ##

# parameters
hist_colors <- c("#009900FF", "#00c000")

# plot_1 for shiny app
x_max <- (round(max(data_plot_distance_traveled_navajoflats$distance_traveled_mi) / 5) * 5) + 5 # max x rounded to nearest 5
center_bin <- 
  if (max(data_plot_distance_traveled_navajoflats$distance_traveled_mi) > 100) {
    round((max(data_plot_distance_traveled_navajoflats$distance_traveled_mi) / 100) / 5) * 5
  } else if (max(data_plot_distance_traveled_navajoflats$distance_traveled_mi) > 50) {
    round((max(data_plot_distance_traveled_navajoflats$distance_traveled_mi) / 10) / 5) * 5
  } else {
    0.5
  }

split_all <- data.frame(table(cut(x = data_plot_distance_traveled_navajoflats$distance_traveled_mi, 
                                       breaks = seq(0, 
                                                    x_max,
                                                    center_bin * 2))))

plot_distance_traveled_navajoflats <-
  ggplot(data = data_plot_distance_traveled_navajoflats) +
  geom_histogram(aes(x = distance_traveled_mi,
                     text = paste0(scales::comma(round(..count.. / nrow(data_plot_distance_traveled_navajoflats), 2) * 100), 
                                   "% of all reservations traveled between ", xmin, " and ", xmax, " miles",
                                   "<br>(", scales::comma(..count..), " reservations)"), 
                     color = "red"),
                 binwidth = center_bin * 2,
                 center = center_bin,
                 fill = hist_colors[[1]], 
                 col = hist_colors[[2]], size = 0.05, color = "red") +
  scale_x_continuous(limits = c(0, x_max)) +
  scale_y_continuous(labels = scales::comma) +
  geom_vline(xintercept = quant_80,
             linetype = "dashed", alpha = 0.5, color = "darkred") +
  annotate(geom = "text",
           x = quant_80,
           y = max(split_all$Freq) * (9/10),
           label ="80th\npercentile",
           size = 3, color = "darkred", hjust = -1) +
  labs(x = "Distance traveled (miles)",
       y = "",
       title = "Distance Traveled to Reservation for <br>Navajo Flats Campground, Los Padres National Forest in 2018") +
  theme_minimal() +
  theme(plot.background = element_rect("white"),
        panel.grid.major.y = element_blank())
```


```{r}
ggplotly(plot_distance_traveled_navajoflats,
         tooltip = list("text")) %>% 
  layout(margin = list(b = 130, t = 100), 
         annotations =  list(x = 1, 
                             y = -0.35, 
                             text = paste0("80% of reservations to California overnight sites in ",
                                           deparse(substitute(data_ridb_acs_2018)) %>% str_remove(".*_"),
                                           " traveled less than ", quant_80, " miles."), 
                             showarrow = F, 
                             xre = 'paper', yref = 'paper', 
                             xanchor = 'left', 
                             yancho = 'auto', 
                             xshift = 0, yshift = 0,
                             font = list(size = 12, color = "darkred")))
```









```{r, eval=FALSE}

## -- data wrangle -- ##
data_plot_distance_traveled_all <- data_ridb_acs_2018 %>% 
  mutate(distance_traveled_mi = distance_traveled_m * 0.000621371) %>% 
  select(agency, admin_unit, park, distance_traveled_mi) %>% 
  filter(!is.na(distance_traveled_mi))

quant_80 <- quantile(x = data_plot_distance_traveled_all$distance_traveled_mi,
                     probs = seq(0, 1, 0.1))[[9]] %>% round(0)


## -- create plot -- ##

# parameters
hist_colors <- c("#009900FF", "#00c000")


test <-
  ggplot(data = data_plot_distance_traveled_all) +
  geom_bar(aes(x = distance_traveled_mi#,
               # text = paste0(scales::comma(round(..count.. / nrow(data_plot_distance_traveled_all), 2) * 100), 
               #               "% of all reservations traveled between ", xmin, " and ", xmax, " miles",
               #               "<br>(", scales::comma(..count..), " reservations)")
               ),
           
           # binwidth = center_bin * 2,
           # center = center_bin,
           fill = hist_colors[[1]], 
           col = hist_colors[[2]], size = 0.05) +
  scale_x_binned() +
  scale_y_continuous(labels = scales::comma) +
  annotate(geom = "text",
           x = ,
           y = ,
  )
annotate(geom = "text", 
         x = x_max / 3, 
         y = (max(split_all$Freq) - min(split_all$Freq)) / 2,
         label = paste0("80% of reservations to \nCalifornia overnight sites in ",
                        deparse(substitute(data_ridb_acs_2018)) %>% str_remove(".*_"),
                        "\n traveled less than ", quant_80, " miles.")) +
  geom_vline(xintercept = quant_80,
             linetype = "dashed", alpha = 0.5) +
  labs(x = "Distance traveled (miles)",
       y = "",
       title = "Distance Traveled from Home to Site for <br>Overnight Reservations in California in 2018") +
  theme_minimal() +
  theme(plot.background = element_rect("white"),
        panel.grid.major.y = element_blank())
```

```{r, eval=FALSE}
ggplotly(test,
         tooltip = list("text"))
```

