---
title: "Data Viz for Shiny App"
author: "Clarissa"
date: "3/16/2022"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

library(tidyverse)
library(here)
library(janitor)
library(lubridate)
library(tidycensus)
library(patchwork)
library(scales)
library(vroom)
library(plotly)

options(scipen = 999)

# for testing plotly outside of shiny
siteInput <- "The Best Site"
admin_unitInput <- "Federal Park/Forest/Etc"
```


```{r}
start_time <- Sys.time()
```

```{r load data}
# read in joined data
data_ridb_acs_2018 <- vroom(file = "../../../../data_clean/2018_joined_data.csv",
                            delim = ",")
# data_ridb_acs_2018 <- readRDS(file = "../../../../data_clean/2018_joined_data.rds") # don't use RDS for non-map viz

# ACS CA data
data_ca_acs_2018 <- vroom(file = "../../../../data_clean/2018_ca_acs_all.csv",
                          delim = ",")

```



## Agency Analysis: Distribution Graphs

### Distance traveled

```{r}
## -- data wrangle -- ##
data_plot_distance_traveled <- data_ridb_acs_2018 %>% 
  mutate(distance_traveled_mi = distance_traveled_m * 0.000621371) %>% 
  select(park, distance_traveled_mi) %>% 
  filter(!is.na(distance_traveled_mi))

x_max <- (round(max(data_plot_distance_traveled$distance_traveled_mi) / 5) * 5) + 5 # max x rounded to nearest 5

center_bin <-
  if (x_max > 100) {
    round((max(data_plot_distance_traveled$distance_traveled_mi) / 100) / 5) * 5
  } else if (x_max > 10) {
    round((max(data_plot_distance_traveled$distance_traveled_mi) / 10) / 5) * 5
  } else {
    0.5
  }

quant_80 <- quantile(x = data_plot_distance_traveled$distance_traveled_mi,
                     probs = seq(0, 1, 0.1))[[9]] %>% round(0)

## -- create plot -- ##

# parameters
hist_colors <- c("#009900FF", "#00c000")

# plot for shiny app
plot_distance_traveled <- ggplot(data = data_plot_distance_traveled) +
  geom_histogram(aes(x = distance_traveled_mi,
                     text = paste0(percent(..count.. / nrow(data_plot_distance_traveled), accuracy = 0.1), 
                                   " of all reservations traveled between ", comma(xmin, accuracy = 1), " and ", 
                                   comma(xmax, accuracy = 1), " miles", "<br>(All reservations to site: ",
                                   comma(nrow(data_plot_distance_traveled), accuracy = 1), ")")),
                 binwidth = center_bin * 2,
                 center = center_bin,
                 fill = hist_colors[[1]], 
                 col = hist_colors[[2]], size = 0.05) +
  scale_x_continuous(limits = c(0, x_max)) +
  scale_y_continuous(labels = comma) +
  geom_vline(xintercept = quant_80,
             linetype = "dashed", alpha = 0.5, color = "#000099") +
  labs(x = "Distance traveled (miles)",
       y = "",
       title = paste0("Distance Traveled from Home to Reservation for <br>", 
                      siteInput, ", ", admin_unitInput, " in 2018")) +
  theme_minimal() +
  theme(plot.background = element_rect("white"),
        panel.grid.major.y = element_blank())

ggplotly(plot_distance_traveled,
         tooltip = list("text"),
         dynamicTicks = TRUE) %>% 
  layout(margin = list(b = 130, t = 100), 
         annotations =  list(x = 1, 
                             y = -0.5, 
                             text = paste0("80% of reservations to ", siteInput, ", ", admin_unitInput, 
                                           "<br>traveled less than ", quant_80, 
                                           " miles (shown on plot with dotted line)."), 
                             showarrow = F, 
                             xre = 'paper', yref = 'paper', 
                             xanchor = 'left', 
                             yanchor = 'auto', 
                             xshift = 0, yshift = 0,
                             font = list(size = 12, color = "#000099")))
```


### Booking window

```{r}
## -- data wrangle -- ##
data_plot_boooking_window <- data_ridb_acs_2018 %>% 
  filter(booking_window > 0,
         booking_window < 510) %>% 
  select(park, booking_window)

x_max <- (round(max(data_plot_boooking_window$booking_window) / 5) * 5) + 5 # max x rounded to nearest 5

quant_80 <- quantile(x = data_plot_boooking_window$booking_window,
                     probs = seq(0, 1, 0.1))[[9]] %>% round(0)

## -- create plot -- ##

# parameters
hist_colors <- c("#009900FF", "#00c000")

# plot for shiny app
plot_booking_window <- ggplot(data = data_plot_boooking_window) +
  geom_histogram(aes(x = booking_window,
                     text = paste0(percent(..count.. / nrow(data_plot_boooking_window), accuracy = 0.1), 
                                   " of all visits are reserved between ", xmin, " and ", xmax, 
                                   " days before the start of the visit", 
                                   "<br>(All reservations to site: ",
                                   comma(nrow(data_plot_boooking_window), accuracy = 1), ")")),
                 binwidth = 7,
                 center = 7 / 2,
                 fill = hist_colors[[1]], 
                 col = hist_colors[[2]], size = 0.05) +
  labs(x = "Total Days Between Order and Start Date (each bar = 1 week)",
       y = "",
       title = paste0("Number of Days Before a Visit that Reservations are Booked", "<br>for ", 
                      siteInput, ", ", admin_unitInput)) +
  scale_x_continuous(limits = c(0, x_max), breaks = seq(0, x_max, 30)) +
  scale_y_continuous(labels = comma) +
  geom_vline(xintercept = quant_80,
             linetype = "dashed", alpha = 0.5, color = "#000099") +
  geom_vline(xintercept = 180, 
             linetype = "dashed", size = .3, alpha = .5) +
  annotate("text", label = "6 months", 
           x = 210, y = 65000) +
  # geom_vline(xintercept = 360, 
  #            linetype = "dashed", size = .3, alpha = .5) +
  # annotate("text", label = "1 year", 
  #          x = 380, y = 65000) +
  theme_minimal() +
  theme(plot.background = element_rect("white"),
        panel.grid.major.y = element_blank())

ggplotly(plot_booking_window,
         tooltip = list("text"),
         dynamicTicks = TRUE) %>% 
  layout(margin = list(b = 130, t = 100), 
         annotations =  list(x = 1, 
                             y = -0.5, 
                             text = paste0("80% of reservations to ", siteInput, ", ", admin_unitInput, 
                                           "<br> reserve their visit less than ", quant_80, 
                                           " days before the start date (shown on plot with dashed line)."), 
                             showarrow = F, 
                             xre = 'paper', yref = 'paper', 
                             xanchor = 'left', 
                             yanchor = 'auto', 
                             xshift = 0, yshift = 0,
                             font = list(size = 12, color = "#000099")))
```


### Daily cost

```{r}
## -- data wrangle -- ##
data_plot_daily_cost <- data_ridb_acs_2018 %>% 
  filter(daily_cost != "Inf") %>% 
  select(park, daily_cost)

## -- create plot -- ##

# wrangling
x_max <- (round(max(data_plot_daily_cost$daily_cost) / 5) * 5) + 5 # max x rounded to nearest 5

center_bin <-
  if (x_max > 100) {
    round((max(data_plot_daily_cost$daily_cost) / 100) / 5) * 5
  } else if (x_max > 10) {
    round((max(data_plot_daily_cost$daily_cost) / 10) / 5) * 5
  } else {
    0.5
  }

quant_80 <- quantile(x = data_plot_daily_cost$daily_cost,
                     probs = seq(0, 1, 0.1))[[9]] %>% round(0)


# parameters
hist_colors <- c("#009900FF", "#00c000")

# plot for shiny app
plot_daily_cost <- ggplot(data = data_plot_daily_cost) +
  geom_histogram(aes(x = daily_cost, 
                     text = paste0(percent(..count.. / nrow(data_plot_daily_cost), accuracy = 0.1), 
                                   " of all reservations paid between ", dollar(xmin), " and ", dollar(xmax),
                                   "<br>(All reservations to site: ",
                                   comma(nrow(data_plot_boooking_window), accuracy = 1), ")")),
                 binwidth = center_bin * 2,
                 center = center_bin,
                 fill = hist_colors[[1]], 
                 col = hist_colors[[2]], size = 0.05) +
  labs(x = "Daily cost per visit ($)",
       y = "",
       title = paste0("Daily Cost for Visits to <br>", siteInput, 
                      ", ", admin_unitInput, " in 2018")) +
  scale_x_continuous(limits = c(0, x_max), labels = dollar) +
  scale_y_continuous(labels = comma) +
  geom_vline(xintercept = quant_80,
             linetype = "dashed", alpha = 0.5, color = "#000099") +
  theme_minimal() +
  theme(plot.background = element_rect("white"),
        panel.grid.major.y = element_blank())

ggplotly(plot_daily_cost,
         tooltip = list("text"),
         dynamicTicks = TRUE) %>% 
  layout(margin = list(b = 130, t = 100), 
         annotations =  list(x = 1, 
                             y = -0.4, 
                             text = paste0("80% of reservations to ", siteInput, ", ", admin_unitInput, 
                                           "<br>paid less than ", dollar(quant_80), " (shown on plot with dotted line)."), 
                             showarrow = F, 
                             xre = 'paper', yref = 'paper', 
                             xanchor = 'left', 
                             yanchor = 'auto', 
                             xshift = 0, yshift = 0,
                             font = list(size = 12, color = "#000099")))
```



### Daily cost per visitor

```{r}
## -- data wrangle -- ##
data_plot_daily_cost_visitor <- data_ridb_acs_2018 %>% 
  filter(daily_cost_per_visitor != "Inf") %>% 
  select(park, daily_cost_per_visitor)

## -- create plot -- ##

# wrangling
x_max <- (round(max(data_plot_daily_cost_visitor$daily_cost_per_visitor) / 5) * 5) + 5 # max x rounded to nearest 5

quant_80 <- quantile(x = data_plot_daily_cost_visitor$daily_cost_per_visitor,
                     probs = seq(0, 1, 0.1))[[9]] %>% round(0)


# parameters
hist_colors <- c("#009900FF", "#00c000")

# plot for shiny app
plot_daily_cost_visitor <- ggplot(data = data_plot_daily_cost_visitor) +
  geom_histogram(aes(x = daily_cost_per_visitor, 
                     text = paste(percent(..count.. / nrow(data_plot_daily_cost_visitor), accuracy = 0.1), 
                                  "of all reservations paid between", dollar(xmin), "and", dollar(xmax),
                                  "<br>(All reservations to site: ",
                                  comma(nrow(data_plot_daily_cost_visitor), accuracy = 1), ")")),
                 binwidth = 1,
                 center = 0.5,
                 fill = hist_colors[[1]], 
                 col = hist_colors[[2]], size = 0.05) +
  labs(x = "Daily cost per visit ($)",
       y = "",
       title = paste0("Daily Cost for Visits to <br>", siteInput, 
                      ", ", admin_unitInput, " in 2018")) +
  scale_x_continuous(limits = c(0, x_max), labels = dollar) +
  scale_y_continuous(labels = comma) +
  geom_vline(xintercept = quant_80,
             linetype = "dashed", alpha = 0.5, color = "#000099") +
  theme_minimal() +
  theme(plot.background = element_rect("white"),
        panel.grid.major.y = element_blank())

ggplotly(plot_daily_cost_visitor,
         tooltip = list("text"),
         dynamicTicks = TRUE) %>% 
  layout(margin = list(b = 130, t = 100), 
         annotations =  list(x = 1, 
                             y = -0.5, 
                             text = paste0("80% of reservations to ", siteInput, ", ", admin_unitInput, 
                                           "<br>paid less than ", dollar(quant_80), 
                                           " per visitor per day (shown on plot with dotted line)."), 
                             showarrow = F, 
                             xre = 'paper', yref = 'paper', 
                             xanchor = 'left', 
                             yanchor = 'auto', 
                             xshift = 0, yshift = 0,
                             font = list(size = 12, color = "#000099")))
```



### Length of Stay

```{r}
## -- data wrangle -- ##
data_plot_length_of_stay <- data_ridb_acs_2018 %>% 
  select(park, length_of_stay)

x_max <- (round(max(data_plot_length_of_stay$length_of_stay) / 5) * 5) + 5 # max x rounded to nearest 5

quant_80 <- quantile(x = data_plot_length_of_stay$length_of_stay,
                     probs = seq(0, 1, 0.1))[[9]] %>% round(0)

## -- create plot -- ##

# parameters
hist_colors <- c("#009900FF", "#00c000")

# plot for shiny app
plot_length_of_stay <- ggplot(data = data_plot_length_of_stay) +
  geom_histogram(aes(x = length_of_stay,
                     text = paste0(percent(..count.. / nrow(data_plot_length_of_stay), accuracy = 0.1), 
                                   " of all reservations stay between ", comma(xmin, accuracy = 1), " and ", 
                                   comma(xmax, accuracy = 1), " days",  "<br>(All reservations to site: ",
                                   comma(nrow(data_plot_length_of_stay), accuracy = 1), ")")),
                 binwidth = 1,
                 center = 0.5,
                 fill = hist_colors[[1]], 
                 col = hist_colors[[2]], size = 0.05) +
  scale_x_continuous(limits = c(0, x_max)) +
  scale_y_continuous(labels = comma) +
  geom_vline(xintercept = quant_80,
             linetype = "dashed", alpha = 0.5, color = "#000099") +
  labs(x = "Length of visit (days)",
       y = "",
       title = paste0("Length of Visit for Reservations at <br>", 
                      siteInput, ", ", admin_unitInput, " in 2018")) +
  theme_minimal() +
  theme(plot.background = element_rect("white"),
        panel.grid.major.y = element_blank())

ggplotly(plot_length_of_stay,
         tooltip = list("text"),
         dynamicTicks = TRUE) %>% 
  layout(margin = list(b = 130, t = 100), 
         annotations =  list(x = 1, 
                             y = -0.4, 
                             text = paste0("80% of reservations to ", siteInput, ", ", admin_unitInput, 
                                           "<br>stay less than ", quant_80, " days (shown on plot with dashed line)."), 
                             showarrow = F, 
                             xre = 'paper', yref = 'paper', 
                             xanchor = 'left', 
                             yanchor = 'auto', 
                             xshift = 0, yshift = 0,
                             font = list(size = 12, color = "#000099")))
```


### Site Type

```{r}
## -- data wrangle -- ##
data_plot_site_type <- data_ridb_acs_2018 %>% 
  select(park, aggregated_site_type) %>% 
  mutate(aggregated_site_type = str_to_title(string = aggregated_site_type),
         aggregated_site_type = str_replace(string = aggregated_site_type,
                                            pattern = "Rv",
                                            replacement = "RV")) %>% 
  count(aggregated_site_type)


## -- create plot -- ##

# parameters
hist_colors <- c("#009900FF")

# plot for shiny app
plot_site_type <- ggplot(data = data_plot_site_type) +
  geom_col(aes(x = n/sum(n), 
               y = reorder(aggregated_site_type, n), 
               text = paste0(percent(n/sum(n), accuracy = 1), " of reservations were made to ", 
                             aggregated_site_type, " sites", "<br>(All reservations to site: ",
                             comma(sum(n), accuracy = 1), ")")),
           fill = hist_colors) +
  scale_x_continuous(labels = percent) +
  labs(x = "Percentage of Reservations to Selected Site",
       y = "",
       title = paste0("Number of Visits by Site Type for <br>", 
                      admin_unitInput, ", ", siteInput, "in 2018")) +
  theme_minimal() +
  theme(plot.background = element_rect("white"),
        panel.grid.major.y = element_blank())

ggplotly(plot_site_type,
         tooltip = list("text"),
         dynamicTicks = TRUE)
```


### Race

```{r}
## -- data wrangle -- ##

# reservations in CA
data_plot_race_ridb <- data_ridb_acs_2018 %>%
  summarize(white = mean(white, na.rm = TRUE),
            black = mean(black, na.rm = TRUE),
            asian = mean(asian, na.rm = TRUE),
            multiracial = mean(multiracial, na.rm = TRUE),
            other = mean(other, na.rm = TRUE),
            native_american = mean(native_american, na.rm = TRUE),
            pacific_islander = mean(pacific_islander, na.rm = TRUE),
            hispanic_latinx = mean(hispanic_latinx, na.rm = TRUE),
            num_reservations = n()) %>%
  pivot_longer(cols = 1:8, names_to = "race", values_to = "race_percent_average") %>% 
  mutate(race = str_replace(string = race,
                            pattern = "_",
                            replacement = " "),
         race = str_to_title(race))

# CA population
data_plot_race_ca <- data_ca_acs_2018 %>%
  summarize(white = weighted.mean(white, mean_zip_code_population, 
                                  na.rm = TRUE),
            black = weighted.mean(black,  mean_zip_code_population,
                                  na.rm = TRUE),
            asian = weighted.mean(asian, mean_zip_code_population, 
                                  na.rm = TRUE),
            multiracial = weighted.mean(multiracial, mean_zip_code_population, 
                                        na.rm = TRUE),
            other = weighted.mean(other, mean_zip_code_population, 
                                  na.rm = TRUE),
            native_american = weighted.mean(native_american, mean_zip_code_population, 
                                            na.rm = TRUE),
            pacific_islander = weighted.mean(pacific_islander, mean_zip_code_population, 
                                             na.rm = TRUE),
            hispanic_latinx = weighted.mean(hispanic_latinx, mean_zip_code_population, 
                                            na.rm = TRUE)) %>%
  pivot_longer(cols = 1:8, names_to = "race", values_to = "race_percent_average") %>% 
  mutate(race = str_replace(string = race,
                            pattern = "_",
                            replacement = " "),
         race = str_to_title(race))

# join data for plotting
data_plot_race <- data_plot_race_ridb %>% 
  left_join(y = data_plot_race_ca,
            by = c("race"),
            suffix = c("_ridb", "_ca")) %>% 
  rename(RIDB = race_percent_average_ridb,
         CA = race_percent_average_ca) %>% 
  pivot_longer(cols = 3:4,
               names_to = "data_source",
               values_to = "race_percent_average") %>% 
  mutate(data_source = factor(data_source, levels = c("RIDB", "CA")),
         tooltip_start = case_when(data_source == "RIDB" ~ "Visitors to California sites live in communities with an <br>estimated ",
                                   data_source == "CA" ~ ""),
         tooltip_middle = case_when(data_source == "RIDB" ~ " ",
                                    data_source == "CA" ~ " of Californians are "),
         tooltip_end = case_when(data_source == "RIDB" ~ " populations",
                                 data_source == "CA" ~ ""),
         race = str_replace(string = race,
                            pattern = "Other",
                            replacement = "Other Race(s)"))

x_max <- max(data_plot_race$race_percent_average) + 0.1 # max x rounded to nearest 5

## -- create plot -- ##

# parameters
groups_colors_ridb_ca <- c("RIDB" = "#009900FF", "CA" = "#666666")
text_colors_ridb_ca <- c("RIDB" = "#006600", "CA" = "#282828")

# plot for shiny app
plot_race <- 
  ggplot(data = data_plot_race) +
  geom_col(aes(x = race_percent_average,
               y = reorder(race, race_percent_average),
               fill = data_source,
               text = paste0(tooltip_start, percent(race_percent_average, accuracy = 0.1), 
                             tooltip_middle, race, tooltip_end)),
           position = "dodge") +
  scale_x_continuous(labels = percent, limits = c(0, x_max)) +
  scale_fill_manual(values = groups_colors_ridb_ca) + 
  geom_text(aes(x = race_percent_average,
                y = reorder(race, race_percent_average),
                label = percent(race_percent_average, accuracy = 0.1),
                col = data_source), 
            position = position_dodge(width = 1), 
            size = 3) +
  scale_color_manual(values = text_colors_ridb_ca) +
  labs(x = "Percentage (%)",
       y = "",
       title = paste0("Estimated Racial Percentages of <br>California Residents vs. Visitors to ", 
                      siteInput, ", ", admin_unitInput)) +
  theme_minimal() +
  theme(plot.background = element_rect("white"),
        panel.grid.major.y = element_blank())

ggplotly(plot_race, 
         tooltip = list("text")) %>%
  style(hoverinfo = "none", traces = c(3, 4),
        textposition = "right") %>% 
  layout(showlegend = FALSE)
```

### Education

```{r}
## -- data wrangle -- ##

# reservations in CA
data_plot_education_ridb <- data_ridb_acs_2018 %>%
  summarize(hs_GED_or_below = mean(hs_GED_or_below, na.rm = TRUE),
            some_college = mean(some_college, na.rm = TRUE),
            college = mean(college, na.rm = TRUE),
            master_or_above = mean(master_or_above, na.rm = TRUE))  %>%
  pivot_longer(cols = 1:4, names_to = "education", values_to = "education_percent_average")

# CA population
data_plot_education_ca <- data_ca_acs_2018 %>%
  summarize(hs_GED_or_below = weighted.mean(hs_GED_or_below, mean_zip_code_population, 
                                            na.rm = TRUE),
            some_college = weighted.mean(some_college, mean_zip_code_population, 
                                         na.rm = TRUE),
            college = weighted.mean(college, mean_zip_code_population, 
                                    na.rm = TRUE),
            master_or_above = weighted.mean(master_or_above, mean_zip_code_population, 
                                            na.rm = TRUE))  %>%
  pivot_longer(cols = 1:4, names_to = "education", values_to = "education_percent_average")

# join data for plotting
data_plot_education <- data_plot_education_ridb %>% 
  left_join(y = data_plot_education_ca,
            by = c("education"),
            suffix = c("_ridb", "_ca")) %>% 
  rename(RIDB = education_percent_average_ridb,
         CA = education_percent_average_ca) %>% 
  pivot_longer(cols = 2:3,
               names_to = "data_source",
               values_to = "education_percent_average") %>% 
  mutate(education = str_replace_all(string = education,
                                     pattern = "_",
                                     replacement = " "),
         education = str_to_title(education),
         education = str_replace(string = education,
                                 pattern = "Hs Ged Or", 
                                 replacement = "HS, GED, or"),
         education = str_replace(string = education,
                                 pattern = "Some College",
                                 replacement = "Some College or Trade School"),
         education = str_replace(string = education,
                                 pattern = "^College$",
                                 replacement = "Associates or Bachelors Degree"),
         education = str_replace(string = education,
                                 pattern = "Master Or Above",
                                 replacement = "Masters Degree or Above"),
         education = factor(education, levels = c("HS, GED, or Below", 
                                                  "Some College or Trade School", 
                                                  "Associates or Bachelors Degree", 
                                                  "Masters Degree or Above")),
         data_source = factor(data_source, levels = c("RIDB", "CA")),
         tooltip_start = case_when(data_source == "RIDB" ~ "Visitors to California sites live in communities with an estimated ",
                                   data_source == "CA" ~ ""),
         tooltip_middle = case_when(data_source == "RIDB" ~ " of the population <br>with ",
                                    data_source == "CA" ~ " of Californians have "),
         tooltip_end = case_when(data_source == "RIDB" ~ " as their highest level of education.",
                                 data_source == "CA" ~ " as their highest level of education."))

x_max <- max(data_plot_education$education_percent_average) + 0.1 # max x rounded to nearest 5

## -- create plot -- ##

# parameters
groups_colors_ridb_ca <- c("RIDB" = "#009900FF", "CA" = "#666666")
text_colors_ridb_ca <- c("RIDB" = "#006600", "CA" = "#282828")

# plot for shiny app
plot_education <- 
  ggplot(data = data_plot_education) +
  geom_col(aes(x = education_percent_average,
               y = education,
               fill = data_source,
               text = paste0(tooltip_start, percent(education_percent_average, accuracy = 0.1), 
                             tooltip_middle, education, tooltip_end)),
           position = "dodge") +
  scale_x_continuous(labels = percent, limits = c(0, x_max)) +
  scale_fill_manual(values = groups_colors_ridb_ca) + 
  geom_text(aes(x = education_percent_average,
                y = education,
                label = percent(education_percent_average, accuracy = 0.1),
                col = data_source), 
            position = position_dodge(width = 1), 
            size = 4) +
  scale_color_manual(values = text_colors_ridb_ca) +
  labs(x = "Percentage (%)",
       y = "",
       title = paste0("Estimated Highest Level of Education of <br>California Residents vs. Visitors to ", 
                      siteInput, ", ", admin_unitInput)) +
  theme_minimal() +
  theme(plot.background = element_rect("white"),
        panel.grid.major.y = element_blank())

ggplotly(plot_education,
         tooltip = list("text")) %>%
  style(hoverinfo = "none", traces = c(3, 4),
        textposition = "right") %>% 
  layout(showlegend = FALSE)
```


### Language
CA census (grey) not yet weighted by population

```{r}
## -- data wrangle -- ##

# reservations in CA
data_plot_language_ridb <- data_ridb_acs_2018 %>%
  select(park, not_english_only, english_only) %>% 
  drop_na(not_english_only, english_only) %>% 
  mutate(mean_zip_code_population = 1) %>% 
  rename(location_indicator = park) %>% 
  relocate(mean_zip_code_population, .before = not_english_only) %>% 
  mutate(data_source = "Visitors to California Sites")

# CA population
data_plot_language_ca <- data_ca_acs_2018 %>%
  select(zip_code, mean_zip_code_population, not_english_only, english_only) %>% 
  drop_na(not_english_only, english_only) %>% 
  rename(location_indicator = zip_code) %>% 
  mutate(data_source = "California Residents")

data_plot_language <- rbind(data_plot_language_ridb, data_plot_language_ca)


## -- create plot -- ##

# parameters
color_ridb_ca <- c("Visitors to California Sites" = "#009900FF", 
                   "California Residents" = "#666666")
fill_ridb_ca <- c("Visitors to California Sites" = "#00c000", 
                  "California Residents" = "#848484")

# ca_colors <- c("#666666", "#848484")
# ridb_colors <- c("#009900FF", "#00c000")

# plot for shiny app
plot_language <- ggplot() +
  geom_density(data = data_plot_language,
               aes(x = not_english_only,
                   color = data_source,
                   fill = data_source,
                   weight = mean_zip_code_population, 
                   text = data_source),
               alpha = 0.5) +
  scale_fill_manual(values = fill_ridb_ca) +
  scale_color_manual(values = color_ridb_ca) +
  scale_x_continuous(labels = percent) +
  labs(x = "Percentage of Population that Speaks a Language Other than English at Home",
       y = "Density",
       title = paste0("Non-English Spken in the Home of <br>California Residents vs. Visitors to ", 
                      siteInput, ", ", admin_unitInput)) +
  theme_minimal() +
  theme(plot.background = element_rect("white"),
        panel.grid.major.y = element_blank())

ggplotly(plot_language, 
         tooltip = list("text")) %>% 
  layout(showlegend = FALSE)
```



### Median income
CA census (grey) not yet weighted by population

```{r}
## -- data wrangle -- ##

# reservations in CA
data_plot_median_income_ridb <- data_ridb_acs_2018 %>%
  select(park, median_income) %>% 
  rename(location_indicator = park) %>% 
  mutate(mean_zip_code_population = 1,
         data_source = "Visitors to California Sites")

# CA population
data_plot_median_income_ca <- data_ca_acs_2018 %>%
  select(zip_code, median_income, mean_zip_code_population) %>% 
  rename(location_indicator = zip_code) %>% 
  mutate(data_source = "California Residents")

data_plot_median_income <- rbind(data_plot_median_income_ridb, data_plot_median_income_ca)


## -- create plot -- ##

# parameters
color_ridb_ca <- c("Visitors to California Sites" = "#009900FF", 
                   "California Residents" = "#666666")
fill_ridb_ca <- c("Visitors to California Sites" = "#00c000", 
                  "California Residents" = "#848484")

# plot for shiny app
plot_median_income <- ggplot() +
  geom_density(data = data_plot_median_income,
               aes(x = median_income,
                   color = data_source,
                   fill = data_source,
                   weight = mean_zip_code_population,
                   text = data_source),
               alpha = 0.5) +
  scale_fill_manual(values = fill_ridb_ca) +
  scale_color_manual(values = color_ridb_ca) +
  scale_x_continuous(labels = dollar) +
  labs(x = "Household Median Income (US $)",
       y = "Density",
       title = paste0("Median-incomes for California Residents vs. <br>Visitors to ", 
                      siteInput, ", ", admin_unitInput)) +
  theme_minimal() +
  theme(plot.background = element_rect("white"),
        panel.grid.major.y = element_blank())

ggplotly(plot_median_income, 
         tooltip = list("text")) %>% 
  layout(showlegend = FALSE)
```




### Total reservations (by agency)

```{r}
## -- data wrangle -- ##

data_plot_agency_park <- data_ridb_acs_2018 %>% 
  group_by(agency, park) %>% 
  summarise(count = n())

## -- create plot -- ##

# plot for shiny app
plot_agency_site <- 
  ggplot(data_plot_agency_park) +
  geom_bar(aes(y = fct_infreq(agency, )), fill = "#009900FF") +
  scale_y_discrete(labels = c("BOR" = "Bureau of Reclamation", "NPS" = "National Park Service", 
                              "USACE" = "US Army Corps of Engineers", "USFS" = "US Forest Service")) +
  scale_x_continuous(limits = c(0, 400), breaks = seq(0, 400, 100), minor_breaks = seq(0, 40, 50)) +
  theme_minimal() +
  labs(fill = "Agency",
       y = "Agency",
       x = "Reservable Site Count",
       title = "Total Sites per Agency \nfor Reservable Overnight Sites in California in 2018") +
  theme(panel.grid.major.y = element_blank(),
        plot.background = element_rect("white"),
        # ## only needed for saving as image
        # axis.text = element_text(size = 12),
        # axis.title = element_text(size = 14, face = "bold"),
        # title = element_text(size = 16, face = "bold")
  )
plot_agency_site
```

### Total Reservations (by agency)

```{r}
## -- data wrangle -- ##

## -- create plot -- ##

# plot for shiny app
plot_agency_visits <- 
  ggplot(data = data_ridb_acs_2018) +
  geom_bar(aes(y = fct_infreq(agency)), fill = "#009900FF") +
  scale_y_discrete(labels = c("BOR" = "Bureau of Reclamation", "NPS" = "National Park Service", 
                              "USACE" = "US Army Corps of Engineers", "USFS" = "US Forest Service")) +
  #scale_x_continuous(limits = c(0, 400), breaks = seq(0, 400, 100), minor_breaks = seq(0, 40, 50)) +
  theme_minimal() +
  labs(y = "",
       x = "Total Reservations per Agency",
       fill = "Agency",
       title = "Total Reservations per Agency \nfor Reservable Overnight Sites in California in 2018") +
  theme(panel.grid.minor.x = element_blank(),
        plot.background = element_rect("white"),
        # ## only needed for saving as image
        # axis.text = element_text(size = 12),
        # axis.title = element_text(size = 14, face = "bold"),
        # title = element_text(size = 16, face = "bold")
  )
plot_agency_visits
```


```{r}
end_time <- Sys.time()
time_taken <- end_time - start_time
time_taken
```



```{r, eval=FALSE}
## Save plot all data to RDS

plot_data <- c("data_plot_distance_traveled", "data_plot_boooking_window", 
               "data_plot_daily_cost", "data_plot_length_of_stay", 
               "data_plot_site_type", "data_plot_race", 
               "data_plot_education", "data_plot_language_ca", 
               "data_plot_language_ridb", "data_plot_median_income_ca",
               "data_plot_median_income_ridb", "data_plot_agency_park")

for (i in seq_along(plot_data)){
  saveRDS(object = get(plot_data[[i]]),
          file = paste0("../../../../data_clean/2018_data_graphs_single_variable/2018_", 
                        plot_data[[i]],
                        ".rds"))
}
```



