---
title: "Data Viz: Final Project"
author: "Halina Do-Linh"
date: "3/8/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(janitor)
library(tidycensus)
library(tmap)
library(sf)
```


# Set up data

```{r}
# load data
# data_combined_2018 <- read.csv("../../../data_clean/2018_joined_data.csv")
```

# Functions

```{r}
# ridb subset pre 2018
source("../analysis/functions/function_ridb_subset-pre2018.R")
# acs median income
source("../analysis/functions/function_acs_median_income.R")
# calculated variables 
source("../analysis/functions/function_ridb_variable_calculate-pre2018.R")
```

```{r}
# read and cleaned and subsetted ridb 2018 data using function
data_ridb_2018 <- RIDB_subset_pre2018("../../data_raw/reservations2018.csv", "CA", 2018)
# read in acs median income data using function
acs_mi_2018 <- acs_subset_calculate_median_income(geography = "zcta",
                                                  year = 2018,
                                                  state = NULL) # not all CA visits are from CA
# combined data
data_combined_2018 <- left_join(data_ridb_2018, acs_mi_2018, 
                                by = c("customer_zip" = "zip_code"))
# add calculated variables
RIDB_calculate_pre2018(data_combined_2018, output_df_name = data_combined_2018)

# add regional_area
data_combined_2018 <- data_combined_2018 %>% 
  mutate(regional_area = case_when(agency == "USFS" ~ parent_location,
                                   agency %in% c("NPS", "BOR", "USACE") ~ region_description)) %>% mutate(regional_area = str_replace(string = regional_area,
                                         pattern = paste(c("NF - FS", "NF -FS", "NF- FS",
                                                           "NF-FS", "-FS", " - FS"), 
                                                         collapse = "|"),
                                         replacement = "National Forest")) %>% 
  mutate(regional_area = str_to_title(regional_area)) 
# noticed not all zips have median incomes?

# add median income stats
data_combined_2018_clean <- data_combined_2018 %>% 
  group_by(park, regional_area, agency) %>%
  summarize(median_median_income = median(median_income, na.rm = TRUE),
            mean_median_income = round(mean(median_income, na.rm = TRUE), 0),
            max_median_income = max(median_income, na.rm = TRUE),
            min_median_income = min(median_income, na.rm = TRUE),
            facility_latitude = mean(facility_latitude),
            facility_longitude = mean(facility_longitude),
            count = n()) %>%
  st_as_sf(coords = c("facility_longitude","facility_latitude"), crs = 4326) %>% # creates geometry column
  ## cleaning up park ##
  mutate(park = str_replace(string = park,
                            pattern = "PYRAMID LAKE / LOS ALAMOS CAMPGROUND",
                            replacement = "PYRAMID LAKE LOS ALAMOS CAMPGROUND")) %>%
  mutate(park = str_replace(string = park,
                            pattern = "Lewis @ French Meadows",
                            replacement = "Lewis at French Meadows")) %>% 
  mutate(park = str_replace(string = park,
                            pattern = "Cg",
                            replacement = "Campground")) %>% 
  mutate(park = str_remove_all(string = park,
                               pattern = paste(c("\\(.*",
                                                 "---.*",
                                                 ",.*"),
                                               collapse = "|")))
                                 
                                 
                               pattern = paste(c("\\(CA\\) --- .*",
                                                 "\\(CA\\)-*"
                                                 #"\\(*",
                                                 "--- .*"),
                                               collapse = "|")))


pattern = paste(c("---", "\\(CA\\)", "-"), collapse = "|")))
(CA) --- FPIN2377
\\(CA\\) --- \W
--- 12390100
(CA)

  
  

# add calculated variables 
# RIDB_calculate_pre2018(data_combined_2018, output_df_name = data_combined_calculated_2018)
# Error in paste(output_df_name) : object 'data_combined_calculated_2018' not found
# RIDB_calculate_pre2018(data_combined_2018, data_combined_2018_clean)
# Error in assign(paste(output_df_name), data.frame(df), envir = .GlobalEnv) : variable names are limited to 10000 bytes
```


```{r}
# set up data
data_combined_2018_clean <- 
  data_combined_2018 %>%
  RIDB_calculate_pre2018(data_combined_2018_clean)
  group_by(park, regional_area, agency) %>%
  summarize(median_median_income = median(median_income, na.rm = TRUE),
            mean_median_income = round(mean(median_income, na.rm = TRUE), 0),
            max_median_income = max(median_income, na.rm = TRUE),
            min_median_income = min(median_income, na.rm = TRUE),
            facility_latitude = mean(facility_latitude),
            facility_longitude = mean(facility_longitude),
            count = n()) %>%
  st_as_sf(coords = c("facility_longitude","facility_latitude"), crs = 4326) %>%
  # lat lon columns are removed and values are moved into geometry column
  filter(park != "BLUE LAKE CAMPGROUND") %>%
  filter(park != "BEAR LAKE CAMPGROUND (CO)")


```




## write `data_combined_2018_clean` as a csv
```{r}
# save as an RDS next time
saveRDS(data_combined_2018_clean, "/capstone/outdoorequity/halina/outdoor-equity/shiny/outdoor-equity-app/data_resMedIncome_CAmap_2018.rds")
```


## write `zip_geometries_ca` as a csv
```{r}
saveRDS(zip_geometries_ca, "/capstone/outdoorequity/halina/outdoor-equity/shiny/outdoor-equity-app/data_zip_geometries_ca.rds")
```


```{r}
# pull in acs CA county data
zip_geometries_ca <- get_acs(geography = "state", year = 2018, geometry = TRUE, 
                             state = "California",
                             summary_var = "B01001_001",
                             variables = c(male = "B01001_002")) %>% 
  select(NAME, geometry)
  
zip_geometries_ca_clean <- zip_geometries_ca %>% 
  mutate(county = str_extract(NAME, "(\\w)([:punct:])"))
  # select(zip_code, geometry)

```

# Map

Pull in median household income for 2018

## histogram of median median income
```{r}
ggplot(data = data_combined_2018_clean, aes(x = median_median_income)) +
  geom_histogram()
```

## histogram of mean median income
```{r}
ggplot(data = data_combined_2018_clean, aes(x = mean_median_income)) +
  geom_histogram()
```

## map of median median income at park sites
```{r}
# add explanatory text about median household income for US
tmap_mode("view") # plot
tm_shape(zip_geometries_ca) +
  tm_polygons(interactive = FALSE) + # this layer doesn't need to be interactive and this removes the popup vars
tm_shape(data_combined_2018_clean) +
  tm_view(view.legend.position = c("bottom", "right")) + # doesn't work for interactive maps??
  tm_symbols(size = "count",
             col = "mean_median_income",
             alpha = 0.8,
             title.col = "Estimated Household Income of Visitor ZIP Code",
             style = "jenks",
             palette = "viridis",
             popup.vars = c("Agency" = "agency",
                            "Number of Reservations" = "count", 
                            "Estimated Household Income" = "mean_median_income"))
             # legend.hist = TRUE) can't use histogram for interactive map
  
# had to remove two points 

## OLD CODE ##
  # tm_shape(shapefile_with_MNO_data) + 
  # tm_dots("MNO_variable")
  # tm_fill(col = "number_reservations",
  #         palette = "PuRd",
  #         style = "jenks",
  #         n = 10)
  # tm_layout(title = "Median Income of Visitors' Home ZIP at Reservable Sites in CA",
  #           legend.position = c("left", "bottom"))
             # breaks = c(40000, 50000, 60000, 70000, 80000, 90000, 100000, 150000, 200000),
```

