---
title: "Scratch HD"
author: "Halina Do-Linh"
date: "2/24/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
```


## Task: Standarize ZIP coe

```{r}
# load raw data
# here() -> "/Users/halina"
data_ridb_2018 <- read_csv(here::here("../../capstone/outdoorequity/data_raw/reservations2018.csv"))
```
```{r}
data_clean_ridb_2018 <- data_ridb_2018 %>%
  janitor::clean_names() %>% 
  # 595002 obs
  filter(facility_state == "CA") %>% 
  select(customer_zip) %>% 
  # 29567 unique ZIP codes
  group_by(customer_zip) %>% 
  summarize(count = n()) %>% 
  # remove punct and symbols 29,657
  mutate(customer_zip = str_remove(string = customer_zip,
                                   pattern = paste(c("[:punct:]",
                                                     "[:symbol:]"),
                                                   collapse = "|"))) %>% 
  # filter strings that are 5 characters 16,902
  filter(customer_zip == str_subset(customer_zip, "[[:digit:]]{5}"))
```


load in data, `clean_names()`, subset to California and overnight reservable sites
```{r}
ridb2018 <- read_csv(here::here("../../data_raw/reservations2018.csv")) %>% 
  clean_names() %>% 
  filter(facility_state == "CA") %>% 
  filter(use_type == "Overnight")
## 451 of sites in CA ##
  # group_by(park) %>%
  # summarize(counts = n())


```


```{r}
ridb2018_zip <- ridb2018 %>% 
  select(c(park, facility_state, customer_zip)) %>% 
  mutate(customer_zip = substr(customer_zip, 1, 5))
  # mutate(customer_zip = str_sub(customer_zip, start = -5, end = -1))
```

```{r}
customer_zip <- c("zxcz", "95409-07")
  # "95409-07"

substr(customer_zip, 1, 5)
```



subset `data_ridb_2018` to one reservable overnight site

```{r}
data_middle_meadows <- data_combined_2018 %>% 
  filter(park == "Middle Meadows --- FPIN151") %>% 
  group_by(customer_zip) %>% 
  count(customer_zip)

racial_middle_meadows_ZIP1 <- data_combined_2018 %>% 
  filter(park == "Middle Meadows --- FPIN151") %>% 
  filter(customer_zip == 94608)
```


```{r}
data_nps <- data_combined_2018 %>% 
  filter(parent_location %in% c("Pacific West Region", "PWR")) %>% 
  filter(region_description == "Yosemite National Park") %>%
  group_by(customer_zip) %>% 
  summarize(count = n())

racial_yosemite_ZIP1 <- data_combined_2018 %>%
  filter(customer_zip == "00001")
```

