---
title: "Notes"
author: "Halina Do-Linh"
date: "4/1/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# testing rmapshaper
#test <- rmapshaper::ms_simplify(data_zip_geometries_ca$geometry)

data_zip_geometries_ca_maptest <- data_zip_geometries_ca %>% rmapshaper::ms_simplify()

# tm_shape(data_zip_geometries_ca) +
#   tm_fill(col = "number_reservations",
#             title = "Number of Visits",
#             palette = "PuRd",
#             style = "jenks",
#             n = 10,
#             popup.vars = c("Total Visits" = "number_reservations")) +
#     tm_shape(data_yosemite_upper_pines_geom) +
#     tm_dots(col = "#009900FF", size = 0.1, alpha = 0.9,
#             id = "park") +
#     tm_view(set.view = c(-119.559917, 37.061753, 6))
```


New things:
- can't reuse inputId's for different pages.

# removed from imported data
```{r}
data_hist_distance_traveled <- readRDS("data/data_hist_distance_traveled.rds")
# agency analysis race hist
data_hist_race <- readRDS("data/2018_data_plot_col_race.rds")
# agency analysis comp dist travel x race 
data_comp_dist_travel_race <- readRDS("data/data_comp_dist_travel_race.rds")
# data need to create regional map for site analysis
data_ca_geom <- readRDS("data/data_ca_geom.rds")
# data_comb_CAmap <- readRDS("data/data_combined_CAmap_2018.rds")
# data_reg_comb <- readRDS("data/data_regional_combined_2018.rds")
```


# server test with print console log
```{r}
  # test
  # reactive DF
  test_df <- reactive ({
    data_test %>% 
      filter(agency %in% input$agency)
  })
  # histogram
  output$vars_single_plot <- renderPlot({
    
    ggplot(data = test_df(), aes(x = length_of_stay)) + 
      geom_histogram() 
    # binary debugging: prints out console log statements
    print(paste0("You have chosen: ", input$agency))
    
  })
```

# code from naoh

```{r}
library(shiny)
library(reactlog)
reactlog::reactlog_enable()

options(shiny.reactlog = TRUE)

  output$agency_analysis <- renderPlot({
    
    ggplot(data = data_joined_2018, aes(x = number_of_people)) + 
      geom_histogram()
    
  })
  
  eventReactive(input$vars_single, {
    cat("Showing", input$vars_single, "rows\n")
    print(paste0("You have chosen: ", input$vars_single))
  })
  
  observeEvent(input$vars_single, {
    cat("Showing", input$vars_single, "rows\n")
    print(paste0("You have chosen: ", input$vars_single))
  })
  
  #update input choices using observe event ----
  observeEvent(input$agency, {
    print(paste0("You have chosen: ", input$agency))
    test <- data_joined_2018 %>%
      filter(agency %in% input$agency)

    admin_test <- as.vector(unique(test$regional_area))

    updateSelectizeInput(session, "agency",
      choices = admin_test
    )

  })
```



# List of input id's

agency 

# List of output id's

data_download

# Shortcuts 

TO = title of
SO = start of 
EO = end of
SEL = select
OP = output
IP = input
OE = observe event