---
title: "Data Cleaning"
author: "Clarissa Boyajian and Halina Do-Linh"
date: "1/24/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(janitor)
library(lubridate)
library(vroom)
library(sf)
library(tidycensus)
library(zipcodeR)
library(tmap)
library(tigris)
library(rmapshaper)

options(scipen = 999)

# RIDB functions
# data subset
source("functions/function_ridb_subset-pre2018.R")
source("functions/function_ridb_subset-post2019.R")
# clean data and calculate variables
source("functions/function_ridb_variable_calculate-pre2018.R")

# ACS functions
source("functions/function_acs_race.R")
source("functions/function_acs_median_income.R")
source("functions/function_acs_education.R")
source("functions/function_acs_language.R")

# join RIDB and ACS function
source("functions/function_join_ridb_acs.R")
```

# RIDB - read in data, calculate varibales, standardize values

```{r}
## 2018 CA
# read in data subset for specific year and state 
data_ridb_2018_subset <- RIDB_subset_pre2018(full_file_path = "../../data_raw/reservations2018.csv", 
                                      state_abbrev = "CA", year = 2018)
# clean and calculate variables
data_ridb_2018_clean <- RIDB_calculate_pre2018(input_df_name = data_ridb_2018_subset)
```

```{r}
# check all agency, admin_unit, and park strings look correct
# check there are no duplicate parks at different admin units
admin_unit_park_check <- data_ridb_2018_clean %>% 
  select(agency, admin_unit, park) %>% 
  unique() %>% 
  relocate(park, .before = 1) %>% 
  arrange(park)
View(admin_unit_park_check)
```



# Census Data - API set up, read, subset, calculate values

```{r, message=FALSE}
# API set up

# # ONLY HAVE TO RUN THE FIRST TIME USING THIS RMD on a new machine
# census_api <- source("private/census-api.R")
# census_api_key(key = census_api[[1]], install = TRUE, overwrite = TRUE)
# # run in console:
## readRenviron("~/.Renviron")

# look at option variables
#View(load_variables(2018, "acs5", cache = TRUE))
```

```{r}
# read in, subset, and clean census data for all US ZIP codes
acs_subset_calculate_race(geography = "zcta", year = 2018, state = NULL)
acs_subset_calculate_median_income(geography = "zcta", year = 2018, state = NULL)
acs_subset_calculate_education(geography = "zcta", year = 2018, state = NULL)
acs_subset_calculate_language(geography = "zcta", state = NULL)
```


# Join RIDB and Census

```{r}
data_combined_2018 <- join_ridb_acs_data(ridb_df = data_ridb_2018_clean,
                                         acs_df_race = data_acs_2018_race_percent,
                                         acs_df_education = data_acs_2018_education_percent,
                                         acs_df_median_income = data_acs_2018_median_income,
                                         acs_df_language = data_acs_2020_language_percent)
```


# Create census dataframe for all CA Zip codes

```{r}
# read in census data
acs_subset_calculate_race(geography = "zcta", year = 2018, state = "California")
acs_subset_calculate_education(geography = "zcta", year = 2018, state = "California")
acs_subset_calculate_language(geography = "zcta", state = "California")
acs_subset_calculate_median_income(geography = "zcta", year = 2018, state = "California")
```

```{r}
acs_ca_all <- left_join(x = data_acs_2018_education_percent_California,
                     y = data_acs_2018_median_income_California,
                     by = "zip_code") %>% 
  left_join(y = data_acs_2018_race_percent_California,
            by = "zip_code") %>% 
  left_join(y = data_acs_2020_language_percent_California,
            by = "zip_code")

acs_ca_all <- acs_ca_all %>% 
  mutate(mean_zip_code_population = rowMeans(acs_ca_all[,c(2,8,17)])) %>% 
  select(-c("zip_code_population.x", 
            "zip_code_population.y",
            "zip_code_population"))
```


# Create dataframes for visitorshed maps


```{r}
# ZIP code geometries for CA (get using `tidycensus`)
zip_geometries_ca <- get_acs(geography = "zcta", year = 2018, geometry = TRUE,
                             state = "California",
                             summary_var = "B01001_001",
                             variables = c(male = "B01001_002")) %>%
  select(NAME, geometry) %>%
  mutate(zip_code = str_sub(NAME, start = -5, end = -1)) %>%
  select(zip_code, geometry)

# simplify ZIP geometries for mapping
simple_zip_geometries_ca <- rmapshaper::ms_simplify(input = zip_geometries_ca$geometry)
## BREAKING ##


# state geometries for full US
# state_geometries_us <- get_acs(geography = "state", year = 2018, geometry = TRUE, 
#                              summary_var = "B01001_001",
#                              variables = c(male = "B01001_002")) %>% 
#   select(GEOID, NAME, geometry) %>% 
#   rename(fips = GEOID, state = NAME)

# state geometries for full US
state_geometries_us <- tigris::states(year = 2018) %>%
  select(GEOID, STUSPS, NAME, geometry) %>% 
  rename(fips = GEOID,
         state_abbrev = STUSPS,
         state = NAME)
```


```{r}
# df of states/DC/Puerto Ricos for each ZIP code
fips_list <- c("01", "02", "04", "05", "06", "08", "09", "10", "11", "12", 
               "13", "15", "16", "17", "18", "19", "20", "21", "22", "23", 
               "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", 
               "34", "35", "36", "37", "38", "39", "40", "41", "42", "44", 
               "45", "46", "47", "48", "49", "50", "51", "53", "54", "55", 
               "56", "72")
state_list <- c("AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "DC", "FL",
                "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME",
                "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH",
                "NJ", "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI",
                "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI",
                "WY", "PR")
states_names_list <- c("Alabama", "Alaska", "Arizona", "Arkansas", "California", 
                       "Colorado", "Connecticut", "Delaware", "District of Columbia", 
                       "Florida","Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", 
                       "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine","Maryland", 
                       "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", 
                       "Montana", "Nebraska", "Nevada", "New Hampshire","New Jersey", 
                       "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", 
                       "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island","South Carolina", 
                       "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", 
                       "Washington", "West Virginia", "Wisconsin","Wyoming", "Puerto Rico")
```


```{r}
# create dataframe of state abbreviations and FIPS codes
df_states_fips <- as.data.frame(list(fips = fips_list,
                                     state = state_list,
                                     state_full = states_names_list))

## -- create dataframe of ZIP codes and states they're in -- ##
df_states_zip_codes <- data.frame()

for (i in seq_along(fips_list)){
  state <- zipcodeR::search_fips(state_fips = fips_list[[i]]) %>% 
    select(zipcode, state)
  df_states_zip_codes <- rbind(df_states_zip_codes, state)
}

# add fips codes and full state names ot 
df_states_fips_zip_codes <- df_states_zip_codes %>% 
  left_join(y = df_states_fips,
            by = "state") %>% 
  rename(state_abbrev = state) %>% 
  relocate(fips, .before = 2)
```

```{r}
## -- data wrangle to create map -- ##
data_map_us <- data_ridb_acs_2018 %>% 
  #filter(park == "Upper Pines") %>% 
  left_join(y = df_states_fips_zip_codes,
            by = c("customer_zip" = "zipcode")) %>% 
  group_by(zip_state_abbr, zip_fips) %>% 
  summarize(number_reservations = n()) %>% 
  filter(!is.na(zip_state_abbr))

data_map_us_geometries <- 
  state_geometries_us %>% 
  left_join(y = data_map_us_yosemite_upper_pines,
            by = c("fips" = "zip_fips"))


## -- create map -- ##
tm_shape(data_map_us_geometries) +
  tm_borders(col = "grey", alpha = 0.5) +
  tm_fill(col = "number_reservations",
          title = "Number of Visits",
          palette = "YlGn",
          n = 10, 
          style = "jenks",
          id = "zip_state_abbr", 
          popup.vars = c("Total Visits" = "number_reservations")) +
  tm_view(set.view = c(-101.834335, 40.022356, 3))
```

```{r}
## -- data wrangle to create map -- ##
data_map_ca <- data_ridb_acs_2018 %>% 
  #filter(park == "Upper Pines") %>% 
  group_by(customer_zip) %>% 
  summarize(number_reservations = n()) %>% 
  mutate(customer_zip = as.character(customer_zip))

data_map_ca_geometries <- zip_geometries_ca %>% 
  left_join(data_map_ca_yosemite_upper_pines, by = c("zip_code" = "customer_zip")) %>% 
  mutate(number_reservations = ifelse(is.na(number_reservations), 0, number_reservations))

data_map_ca_park_geom <- data_ridb_acs_2018 %>% 
  filter(park == "Upper Pines") %>% 
  group_by(agency, admin_unit, park) %>% 
  summarise(facility_latitude = median(facility_latitude),
            facility_longitude = median(facility_longitude)) %>% 
  st_as_sf(coords = c("facility_latitude", "facility_longitude"),
           crs = 4326) %>% 
  st_transform(crs = 4269) # using NAD83 because measured in meters


## -- create map -- ##
tm_shape(data_map_ca_geometries) +
  tm_fill(col = "number_reservations",
          title = "Number of Visits",
          palette = "PuRd",
          style = "jenks",
          n = 10, 
          popup.vars = c("Total Visits" = "number_reservations")) +
  tm_shape(data_map_ca_park_geom) +
  tm_dots(col = "#009900FF", size = 0.1, alpha = 0.9,
          id = "park") +
  tm_view(set.view = c(-119.559917, 37.061753, 6))
```




# Saving dataframes

## Save to CSV

```{r}
# full dataset (RIDB and ACS joined)
write.csv(x = data_combined_2018, 
          file = "../../../data_clean/2018_joined_data.csv", 
          row.names = FALSE)

# all acs vars joined
write.csv(x = acs_ca_all,
          "../../../data_clean/2018_ca_acs_all.csv",
          row.names = FALSE)
```

## Save to RDS

```{r}
# bootstrap geometries and reproject to NAD83
data_combined_2018_geometry <- 
  data_combined_2018 %>% 
  st_as_sf(coords = c("facility_latitude", "facility_longitude"),
           crs = 4326) %>% 
  st_transform(crs = 4269) # using NAD83 because measured in meters


## save RDS files to `data` directory within Shiny App directories

# full dataset (RIDB and ACS joined) with geometries
saveRDS(object = data_combined_2018_geometry,
        file = "../shiny/outdoor-equity-app/oe_app/data/2018_joined_data_geometries.rds")

# full dataset (RIDB and ACS joined) without geometries
saveRDS(object = data_combined_2018,
        file = "../shiny/outdoor-equity-app/oe_app/data/2018_joined_data.rds")

# all acs vars joined
saveRDS(object = acs_ca_all,
        file = "../shiny/outdoor-equity-app/oe_app/data/2018_ca_acs_all.rds")
```



