---
title: "Data Cleaning"
author: "Clarissa Boyajian and Halina Do-Linh"
date: "1/24/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(janitor)
library(lubridate)
library(sf)
library(tidycensus)
library(patchwork)
library(scales)
library(tmap)
library(plotly)

options(scipen = 999)

source("functions/function_acs_race.R")

# colors for racial groups
racial_group_colors <- 
  c("darkgreen", # asian
    "darkblue", # black
    "darkmagenta", # multiracial
    "darkred", # other
    "darkgoldenrod1", # white
    "darkorange2", # pacific_islander
    "darkcyan", # native_american
    "darkgrey" # hispanix_latinx
  )
# colors for agencies
agency_colors <- 
  c("#F8766D", # BOR
    "#7CAE00", # NPS
    "#00BFC4", # USFS
    "#C77CFF" # USACE
  )
```

```{r}
## 2018
# read in data
data_combined_2018 <- read.csv("../../../data_clean/2018_joined_data.csv")

# ACS CA race data
zip_geometries <- get_acs(geography = "zcta", year = 2018, geometry = TRUE, 
                          summary_var = "B01001_001",
                          variables = c(male = "B01001_002")) %>% 
  mutate(zip_code = str_sub(NAME, start = -5, end = -1)) %>% 
  select(zip_code, geometry) %>% 
  
```



# VIZ

```{r}
data_map <- data_combined_2018 %>% 
  filter(park == "Santa Cruz Scorpion (CA)") %>% 
  group_by(customer_zip) %>% 
  summarize(number_reservations = n()) %>% 
  mutate(customer_zip = as.character(customer_zip))

data_map_geometries <- zip_geometries %>% 
  left_join(data_map, by = c("zip_code" = "customer_zip")) %>% 
  mutate(number_reservations = ifelse(is.na(number_reservations), 0, number_reservations))

tm_shape(data_map_geometries, 
         projection = sf::st_crs(4269)) + 
  tm_polygons(col = "number_reservations",
          style = "jenks",
          n = 5,
          palette = "Purples",
          title = "test",
          legend.hist = TRUE) + 
  tm_layout(title = "test",
            frame = FALSE,
            legend.outside = TRUE,
            bg.color = "grey70",
            legend.hist.width = 5,
            fontfamily = "Verdana")
```




