---
title: "Metadata exploration"
author: "Halina Do-Linh"
date: "1/26/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(janitor)
library(lubridate)
```

# Read in data and clean
- variables discount and inventory_type doesn't exist in older datasets

```{r}
ridb_2010 <- read_csv(here("data/2010.csv")) %>% 
  clean_names() %>% 
  select(c("agency",
           "parent_location",
           "park",
           "site_type",
           "use_type",
           "facility_state",
           "facility_latitude",
           "facility_longitude",
           "customer_zip",
           "total_paid",
           "start_date",
           "end_date",
           "order_date",
           "number_of_people"))
```



```{r}
ridb_2020 <- read_csv(here("data/FY20-historical-reservations-full.csv")) %>% 
  clean_names() %>% 
  select(c("agency", 
           "regiondescription",
           "parentlocation",
           "park",
           "sitetype",
           "usetype",
           "inventorytype",
           "facilitystate",
           "facilitylatitude",
           "facilitylongitude",
           "customerzip",
           "totalpaid",
           "discount",
           "startdate",
           "enddate",
           "orderdate",
           "numberofpeople"))
  
```

# Exploring metadata

```{r}
usfs_campsite <- read_csv(here("agency-metadata/USFS_metadata.csv"))
```


```{r}
ridb_2020_motor <- ridb_2020 %>% 
  filter(agency == "BLM") %>% 
  filter(sitetype == "Campsite")
```


```{r}
sum(is.na(ridb_2020$park))

class(ridb_2020$park)

length(unique(ridb_2020$park))

unique(ridb_2020$park)

max(ridb_2020$totalpaid)
```

```{r}
ridb_2020_explore <- ridb_2020 %>% 
  filter(facilitystate == "Delaware")
```


```{r}
ridb_2018_explore <- ridb_2018 %>%
  select(c(order_date, number_of_people)) %>% 
  replace_na(list(number_of_people = "unknown")) %>% 
  filter(number_of_people == "unknown") %>% 
  mutate(month = lubridate::month(order_date)) %>% 
  #filter(year %in% c(2019, 2020)) %>% 
  group_by(month) %>% 
  summarize(n())
```


```{r}
ridb_2020_explore <- ridb_2020 %>%
  select(c(orderdate, numberofpeople)) %>% 
  replace_na(list(numberofpeople = "unknown")) %>% 
  filter(numberofpeople == "unknown") %>% 
  mutate(month = lubridate::month(orderdate)) %>% 
  #filter(year %in% c(2019, 2020)) %>% 
  group_by(month) %>% 
  summarize(n())

class(ridb_2020_explore$year)
```


```{r}
ridb_2020_explore <- ridb_2020 %>% 
  select("sitetype") %>% 
  group_by(sitetype) %>% 
  summarize()

```


```{r}
ridb_2020_explore <- ridb_2020 %>% 
  replace_na(list(usetype = "unknown")) %>% 
  filter(usetype == "unknown")
  # group_by(park) %>% 
  # summarize(n = n())

unique(ridb_2020_explore$inventorytype)
```


```{r}
ridb_2020_explore <- ridb_2020 %>%
  mutate(year = lubridate::year(orderdate)) %>% 
  select(c(orderdate, startdate, enddate)) %>% 
  filter(year %in% 2019)
```


```{r}
fp = here::here("data/FY20-historical-reservations-full.csv")

RIDB_cleaning_post2019(full_file_path = fp, 
                       state = "California", 
                       df_name = "RIDB_CA_2020")
```





